#!/bin/sh

# Protected branches
while read local_ref local_sha remote_ref remote_sha; do
    branch_name=${local_ref#refs/heads/}
    
    if [ "$branch_name" = "develop" ] || [ "$branch_name" = "based/develop" ]; then
        echo ""
        echo "❌ Pushing directly to $branch_name is not allowed"
        echo ""
        exit 1
    fi
done

exit 0
