# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

definitions:
  steps:
    - step: &all-in-one
        name: push-to-gcr
        services:
          - docker
        caches:
          - docker
        size: 2x
        image:
          name: node:20
        script:
          # Package the application
          - npm install
          - npm run build
          # Login to GCP
          - echo $GCP_MANAGER_KEY > ./gcloud-api-key.json
          - cat ./gcloud-api-key.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
          # Configure variables
          - export REPO_PROJECT=$GCP_MANAGER_PROJECT
          - BRANCH=`echo $BITBUCKET_BRANCH | tr / - | tr '[:upper:]' '[:lower:]' | xargs`
          - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
          - export DOCKER_IMAGE=us-central1-docker.pkg.dev/mainbox-378714/mainbox/mintral-coordinador-webclient
          # get commit id
          - export DOCKER_TAG=$BRANCH-$BITBUCKET_COMMIT_SHORT
          - echo $DOCKER_TAG
          # Build docker image
          - docker build . -f Dockerfile -t $DOCKER_IMAGE:$DOCKER_TAG
          # Push to GCP
          - docker push $DOCKER_IMAGE:$DOCKER_TAG

pipelines:
  default:
    - step: *all-in-one
