export { createMiotCalendarClient } from "./client.js";
export { MiotCalendarApiError } from "./errors.js";
export type {
  SlotStatus,
  ResourceData,
  SlotData,
  BookingRequest,
  BookingUpdateRequest,
  BookingResponse,
  BookingListResponse,
  CalendarGroupRequest,
  CalendarGroupResponse,
  CalendarFilter,
  CalendarRequest,
  CalendarResponse,
  TimeWindowKind,
  TimeWindowRequest,
  TimeWindowResponse,
  GenerateSlotsRequest,
  GenerateSlotsResponse,
  SlotResponse,
  SlotListResponse,
  UpdateSlotStatusRequest,
  SlotManagerRequest,
  SlotManagerResponse,
  SlotManagerRunResponse,
  ErrorResponse,
  ClientConfig,
} from "./types.js";
