// Datos reales de operación (junio/julio 2026) para los módulos de la Torre.
// Generado desde sistema_resolucion_operacional. No editar a mano.
// GPS_DATA: snapshot del 6 de julio de 2026, señales en movimiento. ENTITY_DATA: síntomas de junio.

export interface GpsProvider {
  name: string;
  assets: number;
  signals: number;
  ppm: number;
  active_dm: number;
  prov_latency_s: number;
  plat_delay_s: number;
}
export interface GpsData {
  meta: {
    window: string;
    desde: string;
    hasta: string;
    source: string;
    std_mbl: number;
    std_mineria: number;
    moving: boolean;
  };
  totals: {
    signals: number;
    assets: number;
    proveedores: number;
    ppm_fleet: number;
    prov_latency_s: number;
    plat_delay_s: number;
  };
  providers: GpsProvider[];
  perMinute: {
    minuto: string;
    signals: number;
    assets: number;
    prov_latency_s: number;
    plat_delay_s: number;
    plat_max: number;
  }[];
}

export interface EntitySymptom {
  name: string;
  c: number;
  icu4: number;
}
export interface Entity {
  name: string;
  total: number;
  gestionables: number;
  con_tratamiento: number;
  validos: number;
  invalidados: number;
  icu4: number;
  conductores?: number;
  assets: number;
  viajes: number;
  carrier?: string;
  symptoms: EntitySymptom[];
}
export interface EntityData {
  meta: { month: string; source: string };
  carriers: Entity[];
  drivers: Entity[];
}

export const GPS_DATA: GpsData = {
  meta: {
    window: "Snapshot del 6 de julio de 2026",
    desde: "2026-07-06 13:36:40.945+00",
    hasta: "2026-07-06 14:36:38+00",
    source: "operación real · en movimiento",
    std_mbl: 12,
    std_mineria: 20,
    moving: true,
  },
  totals: {
    signals: 55190,
    assets: 860,
    proveedores: 28,
    ppm_fleet: 3.96,
    prov_latency_s: 99.5,
    plat_delay_s: 0.5,
  },
  providers: [
    {
      name: "Proveedor 1",
      assets: 66,
      signals: 14033,
      ppm: 10.72,
      active_dm: 1309,
      prov_latency_s: 143.7,
      plat_delay_s: 0.6,
    },
    {
      name: "Proveedor 2",
      assets: 40,
      signals: 7267,
      ppm: 9.29,
      active_dm: 782,
      prov_latency_s: 74.3,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 3",
      assets: 116,
      signals: 5968,
      ppm: 2.29,
      active_dm: 2607,
      prov_latency_s: 298.7,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 4",
      assets: 185,
      signals: 5910,
      ppm: 1.88,
      active_dm: 3139,
      prov_latency_s: 5.6,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 5",
      assets: 50,
      signals: 4022,
      ppm: 4.25,
      active_dm: 946,
      prov_latency_s: 60.7,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 6",
      assets: 17,
      signals: 3590,
      ppm: 7.92,
      active_dm: 453,
      prov_latency_s: 74.3,
      plat_delay_s: 0.6,
    },
    {
      name: "Proveedor 7",
      assets: 7,
      signals: 3265,
      ppm: 15.55,
      active_dm: 210,
      prov_latency_s: 10.1,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 8",
      assets: 25,
      signals: 1539,
      ppm: 3.4,
      active_dm: 453,
      prov_latency_s: 101.5,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 9",
      assets: 56,
      signals: 1325,
      ppm: 1.32,
      active_dm: 1005,
      prov_latency_s: 48.3,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 10",
      assets: 42,
      signals: 1095,
      ppm: 1.27,
      active_dm: 861,
      prov_latency_s: 103.6,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 11",
      assets: 6,
      signals: 960,
      ppm: 5.85,
      active_dm: 164,
      prov_latency_s: 4,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 12",
      assets: 7,
      signals: 877,
      ppm: 7.31,
      active_dm: 120,
      prov_latency_s: 34.6,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 13",
      assets: 5,
      signals: 804,
      ppm: 6.7,
      active_dm: 120,
      prov_latency_s: 41.7,
      plat_delay_s: 0.7,
    },
    {
      name: "Proveedor 14",
      assets: 8,
      signals: 739,
      ppm: 5.28,
      active_dm: 140,
      prov_latency_s: 68.6,
      plat_delay_s: 0.7,
    },
    {
      name: "Proveedor 15",
      assets: 43,
      signals: 694,
      ppm: 1.17,
      active_dm: 592,
      prov_latency_s: 41.5,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 16",
      assets: 23,
      signals: 479,
      ppm: 1.96,
      active_dm: 245,
      prov_latency_s: 16.5,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 17",
      assets: 5,
      signals: 407,
      ppm: 3.91,
      active_dm: 104,
      prov_latency_s: 79.8,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 18",
      assets: 8,
      signals: 388,
      ppm: 3.34,
      active_dm: 116,
      prov_latency_s: 0.6,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 19",
      assets: 3,
      signals: 383,
      ppm: 3.22,
      active_dm: 119,
      prov_latency_s: 1.1,
      plat_delay_s: 0.6,
    },
    {
      name: "Proveedor 20",
      assets: 8,
      signals: 367,
      ppm: 1.92,
      active_dm: 191,
      prov_latency_s: 1,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 21",
      assets: 1,
      signals: 254,
      ppm: 4.54,
      active_dm: 56,
      prov_latency_s: 25.6,
      plat_delay_s: 0.4,
    },
    {
      name: "Proveedor 22",
      assets: 4,
      signals: 202,
      ppm: 2.38,
      active_dm: 85,
      prov_latency_s: 41.8,
      plat_delay_s: 0.7,
    },
    {
      name: "Proveedor 23",
      assets: 1,
      signals: 170,
      ppm: 3.47,
      active_dm: 49,
      prov_latency_s: 19.2,
      plat_delay_s: 0.6,
    },
    {
      name: "Proveedor 24",
      assets: 1,
      signals: 144,
      ppm: 6,
      active_dm: 24,
      prov_latency_s: 21.3,
      plat_delay_s: 0.6,
    },
    {
      name: "Proveedor 25",
      assets: 130,
      signals: 130,
      ppm: 1,
      active_dm: 130,
      prov_latency_s: -0.5,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 26",
      assets: 1,
      signals: 115,
      ppm: 3.19,
      active_dm: 36,
      prov_latency_s: 18.8,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 27",
      assets: 14,
      signals: 56,
      ppm: 1,
      active_dm: 56,
      prov_latency_s: 129.7,
      plat_delay_s: 0.5,
    },
    {
      name: "Proveedor 28",
      assets: 1,
      signals: 7,
      ppm: 3.5,
      active_dm: 2,
      prov_latency_s: 2819.6,
      plat_delay_s: 0.6,
    },
  ],
  perMinute: [
    {
      minuto: "13:36",
      signals: 310,
      assets: 126,
      prov_latency_s: 200.9,
      plat_delay_s: 0.5,
      plat_max: 1.3,
    },
    {
      minuto: "13:37",
      signals: 999,
      assets: 243,
      prov_latency_s: 165.2,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "13:38",
      signals: 970,
      assets: 238,
      prov_latency_s: 149.3,
      plat_delay_s: 0.6,
      plat_max: 1.6,
    },
    {
      minuto: "13:39",
      signals: 976,
      assets: 231,
      prov_latency_s: 147.7,
      plat_delay_s: 0.6,
      plat_max: 1.9,
    },
    {
      minuto: "13:40",
      signals: 911,
      assets: 240,
      prov_latency_s: 153.5,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "13:41",
      signals: 935,
      assets: 226,
      prov_latency_s: 148.9,
      plat_delay_s: 0.5,
      plat_max: 1.4,
    },
    {
      minuto: "13:42",
      signals: 943,
      assets: 247,
      prov_latency_s: 141.3,
      plat_delay_s: 0.5,
      plat_max: 1.4,
    },
    {
      minuto: "13:43",
      signals: 989,
      assets: 246,
      prov_latency_s: 143.1,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "13:44",
      signals: 993,
      assets: 241,
      prov_latency_s: 157.2,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "13:45",
      signals: 992,
      assets: 249,
      prov_latency_s: 134.6,
      plat_delay_s: 0.6,
      plat_max: 1.6,
    },
    {
      minuto: "13:46",
      signals: 1060,
      assets: 262,
      prov_latency_s: 139,
      plat_delay_s: 0.6,
      plat_max: 1.6,
    },
    {
      minuto: "13:47",
      signals: 1071,
      assets: 263,
      prov_latency_s: 158.2,
      plat_delay_s: 0.5,
      plat_max: 1.4,
    },
    {
      minuto: "13:48",
      signals: 1026,
      assets: 263,
      prov_latency_s: 169.2,
      plat_delay_s: 0.5,
      plat_max: 1.5,
    },
    {
      minuto: "13:49",
      signals: 948,
      assets: 266,
      prov_latency_s: 177.9,
      plat_delay_s: 0.5,
      plat_max: 1.3,
    },
    {
      minuto: "13:50",
      signals: 1004,
      assets: 257,
      prov_latency_s: 138.1,
      plat_delay_s: 0.5,
      plat_max: 1.5,
    },
    {
      minuto: "13:51",
      signals: 1011,
      assets: 262,
      prov_latency_s: 134.9,
      plat_delay_s: 0.5,
      plat_max: 1.2,
    },
    {
      minuto: "13:52",
      signals: 1012,
      assets: 250,
      prov_latency_s: 144.4,
      plat_delay_s: 0.5,
      plat_max: 1.3,
    },
    {
      minuto: "13:53",
      signals: 979,
      assets: 239,
      prov_latency_s: 151.8,
      plat_delay_s: 0.5,
      plat_max: 1.5,
    },
    {
      minuto: "13:54",
      signals: 937,
      assets: 244,
      prov_latency_s: 112.6,
      plat_delay_s: 0.5,
      plat_max: 1.5,
    },
    {
      minuto: "13:55",
      signals: 926,
      assets: 244,
      prov_latency_s: 101.7,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "13:56",
      signals: 917,
      assets: 247,
      prov_latency_s: 104.9,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "13:57",
      signals: 907,
      assets: 243,
      prov_latency_s: 97.8,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "13:58",
      signals: 846,
      assets: 239,
      prov_latency_s: 98.1,
      plat_delay_s: 0.6,
      plat_max: 1.2,
    },
    {
      minuto: "13:59",
      signals: 840,
      assets: 233,
      prov_latency_s: 124.8,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "14:00",
      signals: 870,
      assets: 260,
      prov_latency_s: 108.8,
      plat_delay_s: 0.5,
      plat_max: 1.3,
    },
    {
      minuto: "14:01",
      signals: 945,
      assets: 319,
      prov_latency_s: 120.6,
      plat_delay_s: 0.5,
      plat_max: 1.3,
    },
    {
      minuto: "14:02",
      signals: 819,
      assets: 241,
      prov_latency_s: 136.1,
      plat_delay_s: 0.5,
      plat_max: 1.2,
    },
    {
      minuto: "14:03",
      signals: 870,
      assets: 243,
      prov_latency_s: 111.9,
      plat_delay_s: 0.5,
      plat_max: 1.2,
    },
    {
      minuto: "14:04",
      signals: 922,
      assets: 224,
      prov_latency_s: 113.4,
      plat_delay_s: 0.5,
      plat_max: 1.3,
    },
    {
      minuto: "14:05",
      signals: 959,
      assets: 226,
      prov_latency_s: 132.1,
      plat_delay_s: 0.5,
      plat_max: 1.2,
    },
    {
      minuto: "14:06",
      signals: 913,
      assets: 225,
      prov_latency_s: 115.6,
      plat_delay_s: 0.5,
      plat_max: 1.2,
    },
    {
      minuto: "14:07",
      signals: 900,
      assets: 238,
      prov_latency_s: 94.3,
      plat_delay_s: 0.5,
      plat_max: 1.1,
    },
    {
      minuto: "14:08",
      signals: 953,
      assets: 240,
      prov_latency_s: 83.9,
      plat_delay_s: 0.5,
      plat_max: 1.4,
    },
    {
      minuto: "14:09",
      signals: 1004,
      assets: 227,
      prov_latency_s: 87.1,
      plat_delay_s: 0.5,
      plat_max: 1.4,
    },
    {
      minuto: "14:10",
      signals: 926,
      assets: 237,
      prov_latency_s: 82.7,
      plat_delay_s: 0.5,
      plat_max: 1.2,
    },
    {
      minuto: "14:11",
      signals: 875,
      assets: 223,
      prov_latency_s: 74.5,
      plat_delay_s: 0.5,
      plat_max: 1.1,
    },
    {
      minuto: "14:12",
      signals: 925,
      assets: 212,
      prov_latency_s: 82.8,
      plat_delay_s: 0.5,
      plat_max: 1.3,
    },
    {
      minuto: "14:13",
      signals: 925,
      assets: 219,
      prov_latency_s: 78.8,
      plat_delay_s: 0.5,
      plat_max: 1.4,
    },
    {
      minuto: "14:14",
      signals: 910,
      assets: 214,
      prov_latency_s: 73.3,
      plat_delay_s: 0.6,
      plat_max: 1.2,
    },
    {
      minuto: "14:15",
      signals: 973,
      assets: 241,
      prov_latency_s: 62,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:16",
      signals: 991,
      assets: 236,
      prov_latency_s: 65.2,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:17",
      signals: 969,
      assets: 230,
      prov_latency_s: 78.4,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:18",
      signals: 957,
      assets: 220,
      prov_latency_s: 71.5,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:19",
      signals: 930,
      assets: 228,
      prov_latency_s: 66.5,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:20",
      signals: 967,
      assets: 224,
      prov_latency_s: 50.9,
      plat_delay_s: 0.5,
      plat_max: 1.2,
    },
    {
      minuto: "14:21",
      signals: 1033,
      assets: 235,
      prov_latency_s: 55.1,
      plat_delay_s: 0.6,
      plat_max: 1.6,
    },
    {
      minuto: "14:22",
      signals: 990,
      assets: 224,
      prov_latency_s: 56,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:23",
      signals: 907,
      assets: 226,
      prov_latency_s: 56.2,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:24",
      signals: 927,
      assets: 231,
      prov_latency_s: 52.2,
      plat_delay_s: 0.6,
      plat_max: 1.6,
    },
    {
      minuto: "14:25",
      signals: 908,
      assets: 210,
      prov_latency_s: 52.8,
      plat_delay_s: 0.6,
      plat_max: 1.7,
    },
    {
      minuto: "14:26",
      signals: 880,
      assets: 210,
      prov_latency_s: 48.1,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "14:27",
      signals: 919,
      assets: 215,
      prov_latency_s: 46.6,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:28",
      signals: 947,
      assets: 219,
      prov_latency_s: 47.5,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "14:29",
      signals: 856,
      assets: 215,
      prov_latency_s: 56.1,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:30",
      signals: 856,
      assets: 201,
      prov_latency_s: 49.3,
      plat_delay_s: 0.6,
      plat_max: 1.4,
    },
    {
      minuto: "14:31",
      signals: 781,
      assets: 198,
      prov_latency_s: 45.4,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:32",
      signals: 711,
      assets: 176,
      prov_latency_s: 31.6,
      plat_delay_s: 0.6,
      plat_max: 1.3,
    },
    {
      minuto: "14:33",
      signals: 715,
      assets: 181,
      prov_latency_s: 28,
      plat_delay_s: 0.5,
      plat_max: 1.1,
    },
    {
      minuto: "14:34",
      signals: 702,
      assets: 178,
      prov_latency_s: 20.2,
      plat_delay_s: 0.5,
      plat_max: 1.2,
    },
    {
      minuto: "14:35",
      signals: 722,
      assets: 162,
      prov_latency_s: 13,
      plat_delay_s: 0.5,
      plat_max: 1.4,
    },
    {
      minuto: "14:36",
      signals: 331,
      assets: 119,
      prov_latency_s: 5.5,
      plat_delay_s: 0.5,
      plat_max: 1.1,
    },
  ],
};

export const ENTITY_DATA: EntityData = {
  meta: {
    month: "Junio 2026",
    source: "prod_iot_gps · v_trips_symptoms_treatments",
  },
  carriers: [
    {
      name: "Transportista 1",
      total: 21991,
      gestionables: 2013,
      con_tratamiento: 1404,
      validos: 845,
      invalidados: 559,
      icu4: 2016,
      conductores: 65,
      assets: 74,
      viajes: 993,
      symptoms: [
        { name: "Speed Limit Standard", c: 14591, icu4: 1338 },
        { name: "Lost Signal", c: 3536, icu4: 39 },
        { name: "Continuous Drive Check", c: 985, icu4: 162 },
        { name: "No Authorized Zone Stop", c: 949, icu4: 208 },
        { name: "Deviation_Eta_Early", c: 475, icu4: 70 },
        { name: "Risk Zone Stop", c: 423, icu4: 4 },
        { name: "Continuous Resting Check", c: 351, icu4: 149 },
        { name: "Off Hours Driving", c: 336, icu4: 0 },
        { name: "Deviation_Eta_Late", c: 178, icu4: 46 },
        { name: "Fatigue And Drowsiness Sensor", c: 167, icu4: 0 },
      ],
    },
    {
      name: "Transportista 2",
      total: 2313,
      gestionables: 216,
      con_tratamiento: 242,
      validos: 151,
      invalidados: 91,
      icu4: 258,
      conductores: 25,
      assets: 19,
      viajes: 47,
      symptoms: [
        { name: "Speed Limit Standard", c: 997, icu4: 91 },
        { name: "Lost Signal", c: 821, icu4: 11 },
        { name: "Continuous Drive Check", c: 167, icu4: 33 },
        { name: "No Authorized Zone Stop", c: 125, icu4: 44 },
        { name: "Deviation_Eta_Early", c: 74, icu4: 36 },
        { name: "Continuous Resting Check", c: 59, icu4: 40 },
        { name: "Deviation_Eta_Late", c: 41, icu4: 3 },
        { name: "Off Hours Driving", c: 26, icu4: 0 },
        { name: "Risk Zone Stop", c: 3, icu4: 0 },
      ],
    },
    {
      name: "Transportista 3",
      total: 2094,
      gestionables: 267,
      con_tratamiento: 488,
      validos: 184,
      invalidados: 304,
      icu4: 411,
      conductores: 13,
      assets: 14,
      viajes: 52,
      symptoms: [
        { name: "Speed Limit Standard", c: 1017, icu4: 104 },
        { name: "Lost Signal", c: 506, icu4: 141 },
        { name: "Continuous Drive Check", c: 250, icu4: 73 },
        { name: "No Authorized Zone Stop", c: 116, icu4: 37 },
        { name: "Deviation_Eta_Late", c: 49, icu4: 6 },
        { name: "Double Driver Rotation Check", c: 46, icu4: 0 },
        { name: "Continuous Resting Check", c: 44, icu4: 24 },
        { name: "Deviation_Eta_Early", c: 34, icu4: 25 },
        { name: "Off Hours Driving", c: 22, icu4: 0 },
        { name: "Risk Zone Stop", c: 10, icu4: 1 },
      ],
    },
    {
      name: "Transportista 4",
      total: 1830,
      gestionables: 186,
      con_tratamiento: 282,
      validos: 177,
      invalidados: 105,
      icu4: 248,
      conductores: 19,
      assets: 19,
      viajes: 77,
      symptoms: [
        { name: "Lost Signal", c: 655, icu4: 14 },
        { name: "Speed Limit Standard", c: 564, icu4: 52 },
        { name: "No Authorized Zone Stop", c: 213, icu4: 64 },
        { name: "Continuous Drive Check", c: 110, icu4: 23 },
        { name: "Continuous Resting Check", c: 80, icu4: 48 },
        { name: "Deviation_Eta_Late", c: 69, icu4: 2 },
        { name: "Deviation_Eta_Early", c: 52, icu4: 34 },
        { name: "Off Hours Driving", c: 51, icu4: 1 },
        { name: "Risk Zone Stop", c: 36, icu4: 10 },
      ],
    },
    {
      name: "Transportista 5",
      total: 1812,
      gestionables: 73,
      con_tratamiento: 193,
      validos: 127,
      invalidados: 66,
      icu4: 166,
      conductores: 15,
      assets: 9,
      viajes: 182,
      symptoms: [
        { name: "Lost Signal", c: 757, icu4: 32 },
        { name: "Speed Limit Standard", c: 690, icu4: 59 },
        { name: "No Authorized Zone Stop", c: 164, icu4: 47 },
        { name: "Deviation_Eta_Late", c: 71, icu4: 21 },
        { name: "Deviation_Eta_Early", c: 69, icu4: 5 },
        { name: "Off Hours Driving", c: 49, icu4: 0 },
        { name: "Continuous Drive Check", c: 7, icu4: 0 },
        { name: "Continuous Resting Check", c: 5, icu4: 2 },
      ],
    },
    {
      name: "Transportista 6",
      total: 1449,
      gestionables: 88,
      con_tratamiento: 188,
      validos: 81,
      invalidados: 107,
      icu4: 167,
      conductores: 4,
      assets: 5,
      viajes: 19,
      symptoms: [
        { name: "Lost Signal", c: 854, icu4: 69 },
        { name: "Speed Limit Standard", c: 379, icu4: 39 },
        { name: "Continuous Drive Check", c: 95, icu4: 19 },
        { name: "No Authorized Zone Stop", c: 40, icu4: 17 },
        { name: "Deviation_Eta_Late", c: 32, icu4: 0 },
        { name: "Continuous Resting Check", c: 19, icu4: 6 },
        { name: "Deviation_Eta_Early", c: 17, icu4: 16 },
        { name: "Risk Zone Stop", c: 13, icu4: 1 },
      ],
    },
    {
      name: "Transportista 7",
      total: 1440,
      gestionables: 128,
      con_tratamiento: 173,
      validos: 59,
      invalidados: 114,
      icu4: 208,
      conductores: 13,
      assets: 13,
      viajes: 24,
      symptoms: [
        { name: "Lost Signal", c: 789, icu4: 64 },
        { name: "Speed Limit Standard", c: 467, icu4: 68 },
        { name: "Continuous Drive Check", c: 83, icu4: 27 },
        { name: "No Authorized Zone Stop", c: 44, icu4: 16 },
        { name: "Continuous Resting Check", c: 20, icu4: 14 },
        { name: "Deviation_Eta_Early", c: 19, icu4: 14 },
        { name: "Deviation_Eta_Late", c: 14, icu4: 5 },
        { name: "Risk Zone Stop", c: 2, icu4: 0 },
        { name: "Off Hours Driving", c: 2, icu4: 0 },
      ],
    },
    {
      name: "Transportista 8",
      total: 1320,
      gestionables: 430,
      con_tratamiento: 652,
      validos: 196,
      invalidados: 456,
      icu4: 569,
      conductores: 21,
      assets: 21,
      viajes: 86,
      symptoms: [
        { name: "Lost Signal", c: 697, icu4: 140 },
        { name: "Continuous Drive Check", c: 465, icu4: 363 },
        { name: "No Authorized Zone Stop", c: 50, icu4: 14 },
        { name: "Continuous Resting Check", c: 32, icu4: 27 },
        { name: "Speed Limit Standard", c: 23, icu4: 3 },
        { name: "Deviation_Eta_Early", c: 22, icu4: 19 },
        { name: "Deviation_Eta_Late", c: 20, icu4: 3 },
        { name: "Risk Zone Stop", c: 6, icu4: 0 },
        { name: "Off Hours Driving", c: 5, icu4: 0 },
      ],
    },
  ],
  drivers: [
    {
      name: "Conductor 1",
      carrier: "Transportista 1",
      total: 894,
      gestionables: 114,
      con_tratamiento: 42,
      validos: 18,
      invalidados: 24,
      icu4: 111,
      assets: 1,
      viajes: 8,
      symptoms: [
        { name: "Speed Limit Standard", c: 661, icu4: 86 },
        { name: "Lost Signal", c: 99, icu4: 2 },
        { name: "Off Hours Driving", c: 41, icu4: 0 },
        { name: "Continuous Drive Check", c: 41, icu4: 7 },
        { name: "No Authorized Zone Stop", c: 24, icu4: 7 },
        { name: "Continuous Resting Check", c: 8, icu4: 5 },
        { name: "Fatigue And Drowsiness Sensor", c: 7, icu4: 0 },
        { name: "Risk Zone Stop", c: 6, icu4: 0 },
        { name: "Deviation_Eta_Early", c: 4, icu4: 3 },
        { name: "Deviation_Eta_Late", c: 3, icu4: 1 },
      ],
    },
    {
      name: "Conductor 2",
      carrier: "Transportista 1",
      total: 857,
      gestionables: 100,
      con_tratamiento: 48,
      validos: 21,
      invalidados: 27,
      icu4: 96,
      assets: 1,
      viajes: 10,
      symptoms: [
        { name: "Speed Limit Standard", c: 606, icu4: 62 },
        { name: "Lost Signal", c: 102, icu4: 7 },
        { name: "Continuous Drive Check", c: 50, icu4: 10 },
        { name: "No Authorized Zone Stop", c: 28, icu4: 6 },
        { name: "Continuous Resting Check", c: 24, icu4: 9 },
        { name: "Off Hours Driving", c: 20, icu4: 0 },
        { name: "Risk Zone Stop", c: 12, icu4: 0 },
        { name: "Fatigue And Drowsiness Sensor", c: 8, icu4: 0 },
        { name: "Deviation_Eta_Late", c: 5, icu4: 1 },
        { name: "Deviation_Eta_Early", c: 2, icu4: 1 },
      ],
    },
    {
      name: "Conductor 3",
      carrier: "Transportista 1",
      total: 843,
      gestionables: 107,
      con_tratamiento: 56,
      validos: 28,
      invalidados: 28,
      icu4: 94,
      assets: 3,
      viajes: 12,
      symptoms: [
        { name: "Speed Limit Standard", c: 635, icu4: 64 },
        { name: "Continuous Drive Check", c: 63, icu4: 8 },
        { name: "No Authorized Zone Stop", c: 34, icu4: 6 },
        { name: "Off Hours Driving", c: 27, icu4: 0 },
        { name: "Risk Zone Stop", c: 25, icu4: 0 },
        { name: "Continuous Resting Check", c: 24, icu4: 9 },
        { name: "Deviation_Eta_Early", c: 14, icu4: 7 },
        { name: "Lost Signal", c: 13, icu4: 0 },
        { name: "Deviation_Eta_Late", c: 7, icu4: 0 },
        { name: "Fatigue And Drowsiness Sensor", c: 1, icu4: 0 },
      ],
    },
    {
      name: "Conductor 4",
      carrier: "Transportista 1",
      total: 821,
      gestionables: 76,
      con_tratamiento: 59,
      validos: 34,
      invalidados: 25,
      icu4: 63,
      assets: 2,
      viajes: 15,
      symptoms: [
        { name: "Speed Limit Standard", c: 592, icu4: 43 },
        { name: "Lost Signal", c: 70, icu4: 0 },
        { name: "Continuous Drive Check", c: 48, icu4: 5 },
        { name: "No Authorized Zone Stop", c: 31, icu4: 5 },
        { name: "Off Hours Driving", c: 24, icu4: 0 },
        { name: "Deviation_Eta_Early", c: 22, icu4: 1 },
        { name: "Continuous Resting Check", c: 20, icu4: 9 },
        { name: "Risk Zone Stop", c: 14, icu4: 0 },
      ],
    },
    {
      name: "Conductor 5",
      carrier: "Transportista 1",
      total: 784,
      gestionables: 102,
      con_tratamiento: 70,
      validos: 26,
      invalidados: 44,
      icu4: 110,
      assets: 1,
      viajes: 9,
      symptoms: [
        { name: "Speed Limit Standard", c: 579, icu4: 63 },
        { name: "Lost Signal", c: 102, icu4: 14 },
        { name: "Continuous Drive Check", c: 56, icu4: 21 },
        { name: "No Authorized Zone Stop", c: 26, icu4: 5 },
        { name: "Risk Zone Stop", c: 9, icu4: 0 },
        { name: "Continuous Resting Check", c: 7, icu4: 4 },
        { name: "Deviation_Eta_Early", c: 3, icu4: 3 },
        { name: "Deviation_Eta_Late", c: 2, icu4: 0 },
      ],
    },
    {
      name: "Conductor 6",
      carrier: "Transportista 1",
      total: 784,
      gestionables: 20,
      con_tratamiento: 47,
      validos: 39,
      invalidados: 8,
      icu4: 24,
      assets: 5,
      viajes: 26,
      symptoms: [
        { name: "Speed Limit Standard", c: 640, icu4: 20 },
        { name: "Lost Signal", c: 76, icu4: 0 },
        { name: "Deviation_Eta_Early", c: 39, icu4: 0 },
        { name: "No Authorized Zone Stop", c: 28, icu4: 4 },
        { name: "Fatigue And Drowsiness Sensor", c: 1, icu4: 0 },
      ],
    },
    {
      name: "Conductor 7",
      carrier: "Transportista 1",
      total: 673,
      gestionables: 60,
      con_tratamiento: 21,
      validos: 15,
      invalidados: 6,
      icu4: 65,
      assets: 1,
      viajes: 11,
      symptoms: [
        { name: "Speed Limit Standard", c: 545, icu4: 53 },
        { name: "Lost Signal", c: 46, icu4: 0 },
        { name: "Off Hours Driving", c: 34, icu4: 0 },
        { name: "No Authorized Zone Stop", c: 21, icu4: 6 },
        { name: "Continuous Resting Check", c: 10, icu4: 6 },
        { name: "Risk Zone Stop", c: 9, icu4: 0 },
        { name: "Fatigue And Drowsiness Sensor", c: 5, icu4: 0 },
        { name: "Deviation_Eta_Early", c: 2, icu4: 0 },
        { name: "Continuous Drive Check", c: 1, icu4: 0 },
      ],
    },
    {
      name: "Conductor 8",
      carrier: "Transportista 1",
      total: 658,
      gestionables: 80,
      con_tratamiento: 28,
      validos: 14,
      invalidados: 14,
      icu4: 78,
      assets: 1,
      viajes: 8,
      symptoms: [
        { name: "Speed Limit Standard", c: 498, icu4: 57 },
        { name: "Lost Signal", c: 39, icu4: 0 },
        { name: "Continuous Drive Check", c: 38, icu4: 8 },
        { name: "Risk Zone Stop", c: 26, icu4: 0 },
        { name: "No Authorized Zone Stop", c: 24, icu4: 5 },
        { name: "Off Hours Driving", c: 13, icu4: 0 },
        { name: "Continuous Resting Check", c: 12, icu4: 5 },
        { name: "Deviation_Eta_Late", c: 6, icu4: 1 },
        { name: "Deviation_Eta_Early", c: 2, icu4: 2 },
      ],
    },
    {
      name: "Conductor 9",
      carrier: "Transportista 1",
      total: 646,
      gestionables: 100,
      con_tratamiento: 75,
      validos: 27,
      invalidados: 48,
      icu4: 80,
      assets: 2,
      viajes: 12,
      symptoms: [
        { name: "Speed Limit Standard", c: 353, icu4: 29 },
        { name: "Continuous Drive Check", c: 105, icu4: 24 },
        { name: "Lost Signal", c: 70, icu4: 2 },
        { name: "Off Hours Driving", c: 36, icu4: 0 },
        { name: "No Authorized Zone Stop", c: 35, icu4: 7 },
        { name: "Continuous Resting Check", c: 24, icu4: 12 },
        { name: "Deviation_Eta_Early", c: 10, icu4: 6 },
        { name: "Risk Zone Stop", c: 7, icu4: 0 },
        { name: "Fatigue And Drowsiness Sensor", c: 6, icu4: 0 },
      ],
    },
    {
      name: "Conductor 10",
      carrier: "Transportista 1",
      total: 642,
      gestionables: 67,
      con_tratamiento: 51,
      validos: 36,
      invalidados: 15,
      icu4: 65,
      assets: 1,
      viajes: 25,
      symptoms: [
        { name: "Speed Limit Standard", c: 342, icu4: 38 },
        { name: "Lost Signal", c: 123, icu4: 1 },
        { name: "Off Hours Driving", c: 60, icu4: 0 },
        { name: "No Authorized Zone Stop", c: 34, icu4: 11 },
        { name: "Deviation_Eta_Early", c: 26, icu4: 5 },
        { name: "Continuous Resting Check", c: 17, icu4: 6 },
        { name: "Risk Zone Stop", c: 16, icu4: 1 },
        { name: "Continuous Drive Check", c: 14, icu4: 0 },
        { name: "Fatigue And Drowsiness Sensor", c: 5, icu4: 0 },
        { name: "Deviation_Eta_Late", c: 5, icu4: 3 },
      ],
    },
    {
      name: "Conductor 11",
      carrier: "Transportista 6",
      total: 566,
      gestionables: 46,
      con_tratamiento: 82,
      validos: 31,
      invalidados: 51,
      icu4: 73,
      assets: 1,
      viajes: 7,
      symptoms: [
        { name: "Lost Signal", c: 334, icu4: 29 },
        { name: "Speed Limit Standard", c: 145, icu4: 16 },
        { name: "Continuous Drive Check", c: 55, icu4: 14 },
        { name: "No Authorized Zone Stop", c: 16, icu4: 7 },
        { name: "Deviation_Eta_Early", c: 6, icu4: 5 },
        { name: "Continuous Resting Check", c: 6, icu4: 2 },
        { name: "Risk Zone Stop", c: 3, icu4: 0 },
        { name: "Deviation_Eta_Late", c: 1, icu4: 0 },
      ],
    },
    {
      name: "Conductor 12",
      carrier: "Transportista 1",
      total: 566,
      gestionables: 55,
      con_tratamiento: 47,
      validos: 23,
      invalidados: 24,
      icu4: 37,
      assets: 1,
      viajes: 13,
      symptoms: [
        { name: "Speed Limit Standard", c: 343, icu4: 17 },
        { name: "Lost Signal", c: 77, icu4: 0 },
        { name: "Continuous Drive Check", c: 54, icu4: 7 },
        { name: "Continuous Resting Check", c: 25, icu4: 5 },
        { name: "No Authorized Zone Stop", c: 24, icu4: 8 },
        { name: "Risk Zone Stop", c: 23, icu4: 0 },
        { name: "Deviation_Eta_Early", c: 15, icu4: 0 },
        { name: "Fatigue And Drowsiness Sensor", c: 5, icu4: 0 },
      ],
    },
  ],
};

// Dimensión de comportamiento por síntoma (technicalName).
export function symDim(name: string): string {
  if (
    [
      "Speed Limit Standard",
      "Harsh Braking",
      "Harsh Turn",
      "Harsh Acceleration",
      "Fatigue And Drowsiness",
      "Fatigue And Drowsiness Sensor",
    ].includes(name)
  )
    return "Seguridad de conducción";
  if (
    [
      "Continuous Drive Check",
      "Continuous Resting Check",
      "Off Hours Driving",
      "Double Driver Rotation Check",
    ].includes(name)
  )
    return "Jornada y descanso";
  if (name === "Lost Signal") return "Trazabilidad";
  if (["Deviation_Eta_Early", "Deviation_Eta_Late"].includes(name))
    return "Cumplimiento de plan";
  if (["Risk Zone Stop", "No Authorized Zone Stop"].includes(name))
    return "Exposición a riesgo";
  return "Otros";
}

export const DIM_COLOR: Record<string, string> = {
  "Seguridad de conducción": "bg-blue-600",
  "Jornada y descanso": "bg-blue-400",
  Trazabilidad: "bg-amber-500",
  "Cumplimiento de plan": "bg-green-500",
  "Exposición a riesgo": "bg-rose-500",
  Otros: "bg-gray-400",
};
