// Torre de Control — catálogo de síntomas + datos reales (junio 2026).
// Generado desde la herramienta sistema_resolucion_operacional. No editar a mano.

export const FAMILIES = [
  "Seguridad vial y conducción",
  "Seguridad patrimonial y geográfica",
  "Salud del vehículo y mantenimiento",
  "Eficiencia operacional y planificación",
  "Seguridad de carga, bodega y personas",
  "Observabilidad de datos",
] as const;

export interface Symptom {
  id: string;
  name: string;
  technicalName: string;
  family: number;
  risk: string;
  entities: string[];
  evidence?: string[];
  kpiChip?: string;
  see?: string;
  understand?: string;
  act?: string;
  solve?: string;
  improve?: string;
  kpis?: string[];
  q?: string;
  story?: string;
  owner?: string;
  action?: string;
  special?: string;
}

export interface DayPoint {
  dia: string;
  total: number;
  icu4: number;
  gestionables: number;
  validos: number;
}
export interface DimPoint {
  dim: string;
  total: number;
  icu4: number;
}
export interface Kpis {
  total: number;
  viajes: number;
  conductores: number;
  transportistas: number;
  gestionables: number;
  con_tratamiento: number;
  validos: number;
  invalidados: number;
  icu1: number;
  icu2: number;
  icu3: number;
  icu4: number;
  blackcode: number;
  sla_p50_min: number | null;
  sla_p90_min: number | null;
  trat_5min?: number;
  trat_2h?: number;
}
export interface ProdEntry {
  kpis: Kpis;
  daily: DayPoint[];
  route: DimPoint[];
  carrier: DimPoint[];
  driver: DimPoint[];
}

export const SYMPTOMS: Symptom[] = [
  {
    id: "speed-standard",
    name: "Exceso de velocidad estándar",
    technicalName: "Speed Limit Standard",
    family: 0,
    risk: "Accidente vial, incumplimiento normativo y daño reputacional.",
    entities: [
      "Conductor",
      "Vehículo",
      "Ruta",
      "Tramo",
      "Transportista",
      "Servicio",
    ],
    evidence: [
      "Velocidad GPS",
      "Límite de ruta (OSM)",
      "Timestamp",
      "Geocerca",
      "Historial",
    ],
    kpiChip: "Eventos / 100 viajes",
    see: "Detecta velocidad sobre el umbral general de la ruta, con la magnitud del exceso en km/h.",
    understand:
      "Cruza conductor, tramo, horario, vehículo y reincidencia para saber si es un evento aislado o un patrón.",
    act: "Genera alerta, asigna responsable, contacta al conductor y registra el tratamiento con evidencia.",
    solve:
      "Investiga presión por ETA, desconocimiento de límites, señalización insuficiente o conducta recurrente.",
    improve:
      "Mide reducción de eventos por 100 viajes, reincidencia por conductor y severidad promedio.",
    kpis: [
      "Eventos por 100 viajes",
      "Reincidencia por conductor",
      "Severidad promedio",
      "Reducción mensual",
    ],
    q: "¿Corregimos una conducta puntual o una presión operacional que incentiva la velocidad?",
    story:
      "En junio la velocidad fue el síntoma más frecuente de toda la operación. La pregunta no es cuántos hubo, sino cuántos son conducta y cuántos presión por ETA.",
    owner: "Conductor · gestión de reincidentes",
    action: "Coaching + límite por tramo crítico",
  },
  {
    id: "speed-custom",
    name: "Exceso de velocidad customizado",
    technicalName: "Speed Limit Custom",
    family: 0,
    risk: "Incumplimiento de límites específicos por faena, tramo o contrato del cliente.",
    entities: [
      "Conductor",
      "Tramo",
      "Zona",
      "Cliente",
      "Regla de negocio",
      "Vehículo",
    ],
    evidence: [
      "Velocidad GPS",
      "Límite custom por zona",
      "Geocerca",
      "Timestamp",
      "Historial",
    ],
    kpiChip: "Cumplimiento por tramo",
    see: "Detecta velocidad sobre un límite específico configurado por zona, tramo o cliente.",
    understand:
      "Relaciona límite, ruta, señalética y comportamiento real para validar si la regla y la realidad coinciden.",
    act: "Tratamiento inmediato y registro de evidencia sobre el tramo crítico.",
    solve:
      "Ajusta límites mal parametrizados, refuerza señalización y capacita por tramo crítico.",
    improve:
      "Mide cumplimiento por tramo y reducción de eventos en zonas críticas.",
    kpis: [
      "Cumplimiento por tramo",
      "Eventos por zona crítica",
      "Reincidencia",
      "Reducción mensual",
    ],
    q: "¿El exceso es conducta o una regla mal calibrada para la operación real del tramo?",
    story:
      "El control fino por tramo revela si la regla y la realidad coinciden. Un exceso 'custom' suele ser un límite mal calibrado tanto como una conducta.",
    owner: "Operación · reglas por tramo",
    action: "Ajuste de límite + señalización",
  },
  {
    id: "continuous-drive",
    name: "Conducción máxima continua",
    technicalName: "Continuous Drive Check",
    family: 0,
    risk: "Fatiga, riesgo de accidente e incumplimiento de jornada legal.",
    entities: [
      "Conductor",
      "Ruta",
      "Turno",
      "Planificación",
      "Servicio",
      "Transportista",
    ],
    evidence: [
      "Tiempo de conducción continua",
      "GPS",
      "Movimiento",
      "Timestamp",
      "Puntos de descanso",
    ],
    kpiChip: "Conducción > umbral",
    see: "Detecta tiempo de conducción continua sobre el umbral de jornada, escalando por severidad.",
    understand:
      "Cruza planificación, ruta, presión por ETA y disponibilidad de descansos y relevos.",
    act: "Instruye descanso, escala el riesgo de fatiga y registra la decisión operacional.",
    solve:
      "Rediseña la planificación: ventanas, exigencia de ruta y puntos de relevo antes del umbral.",
    improve:
      "Reduce conducción excesiva y aumenta el cumplimiento de descansos programados.",
    kpis: [
      "Eventos por 100 viajes",
      "Cumplimiento de descanso",
      "% rutas con relevo planificado",
      "Reducción mensual",
    ],
    q: "¿El conductor elige manejar de más o el plan lo obliga sin punto de descanso al alcance?",
    story:
      "Aquí se ve el patrón más incómodo del mes: se trata casi todo, pero la mayoría se invalida. La bandeja se vacía; la fatiga sigue.",
    owner: "Transportista · dotación",
    action: "Relevo/descanso antes de las 5h",
  },
  {
    id: "continuous-resting",
    name: "Descanso mínimo continuo",
    technicalName: "Continuous Resting Check",
    family: 0,
    risk: "Fatiga acumulada por descanso insuficiente y reinicio inseguro de la conducción.",
    entities: ["Conductor", "Viaje", "Parada", "Planificación", "Turno"],
    evidence: [
      "Duración de descanso",
      "Estado de movimiento",
      "Geocerca",
      "Timestamp",
    ],
    kpiChip: "% descansos válidos",
    see: "Detecta descanso insuficiente respecto al estándar antes de reanudar la conducción.",
    understand:
      "Analiza condiciones del viaje, la parada, el conductor y la planificación de tiempos.",
    act: "Notifica el incumplimiento y evita un reinicio inseguro de la operación.",
    solve: "Ajusta el plan de viaje y los protocolos de descanso obligatorio.",
    improve: "Aumenta el % de descansos válidos y reduce la reincidencia.",
    kpis: [
      "% descansos válidos",
      "Reincidencia por conductor",
      "Reducción mensual",
      "Cumplimiento de protocolo",
    ],
    q: "¿El descanso corto es indisciplina o un plan de tiempos que no lo permite?",
    story:
      "El descanso insuficiente no siempre es indisciplina: muchas veces el plan de tiempos no lo permite.",
    owner: "Planificación · tiempos de ruta",
    action: "Paradas de descanso planificadas",
  },
  {
    id: "harsh-braking",
    name: "Frenado brusco",
    technicalName: "Harsh Braking",
    family: 0,
    risk: "Riesgo vial, daño de carga y estilo de manejo peligroso.",
    entities: [
      "Conductor",
      "Ruta",
      "Tramo",
      "Zona",
      "Vehículo",
      "Tipo de carga",
    ],
    evidence: ["Acelerómetro", "Velocidad", "GPS", "Timestamp", "Reincidencia"],
    kpiChip: "Eventos / 1.000 km",
    see: "Detecta un evento de desaceleración brusca sobre umbral.",
    understand:
      "Cruza conductor, ruta, tráfico, carga, zona y reincidencia para separar hábito de condición externa.",
    act: "Alerta y registra el evento, alimentando el score de conducción.",
    solve:
      "Coaching al conductor, revisión de ruta o de la condición operacional del tramo.",
    improve: "Reduce eventos por conductor y por 1.000 km.",
    kpis: [
      "Eventos por 1.000 km",
      "Reincidencia por conductor",
      "Score de conducción",
      "Reducción mensual",
    ],
    q: "¿Es estilo de manejo o un tramo que fuerza frenadas por diseño?",
    story:
      "El frenado brusco distingue estilo de manejo de tramo peligroso. La reincidencia por ruta lo aclara.",
    owner: "Conductor · coaching",
    action: "Coaching + revisión de tramo",
  },
  {
    id: "harsh-turn",
    name: "Giro brusco",
    technicalName: "Harsh Turn",
    family: 0,
    risk: "Riesgo de volcamiento, daño de carga y desgaste del vehículo.",
    entities: ["Conductor", "Curva", "Ruta", "Vehículo", "Tipo de carga"],
    evidence: ["Acelerómetro/giroscopio", "Velocidad", "GPS", "Timestamp"],
    kpiChip: "Eventos por ruta",
    see: "Detecta un evento de giro brusco sobre umbral.",
    understand:
      "Cruza curva, ruta, velocidad, conductor y tipo de vehículo/carga.",
    act: "Registra y alerta si el evento es crítico.",
    solve: "Coaching, rediseño de ruta o advertencias por tramo peligroso.",
    improve: "Reduce eventos por conductor y por ruta.",
    kpis: [
      "Eventos por 1.000 km",
      "Reincidencia por conductor",
      "Eventos por tramo",
      "Reducción mensual",
    ],
    q: "¿Corregimos al conductor o marcamos la curva que repite el evento?",
    story: "El giro brusco casi siempre marca una curva, no solo un conductor.",
    owner: "Conductor · coaching",
    action: "Advertencia por tramo + coaching",
  },
  {
    id: "harsh-accel",
    name: "Aceleración brusca",
    technicalName: "Harsh Acceleration",
    family: 0,
    risk: "Riesgo vial, mayor consumo y estilo de conducción agresivo.",
    entities: [
      "Conductor",
      "Zona",
      "Tipo de operación",
      "Vehículo",
      "Tipo de carga",
    ],
    evidence: ["Acelerómetro", "Velocidad", "GPS", "Timestamp", "Reincidencia"],
    kpiChip: "Score conductor",
    see: "Detecta un evento de aceleración agresiva.",
    understand:
      "Cruza conductor, zona, tipo de operación, carga y reincidencia.",
    act: "Registra, alerta y alimenta el score de conducción.",
    solve: "Coaching y gestión de reincidentes.",
    improve: "Reduce eventos y mejora el score del conductor.",
    kpis: [
      "Eventos por 1.000 km",
      "Score de conducción",
      "Reincidencia",
      "Reducción mensual",
    ],
    q: "¿El score mejora con coaching o solo registramos el evento?",
    story:
      "La aceleración agresiva alimenta el score de conducción y anticipa riesgo y consumo.",
    owner: "Conductor · coaching",
    action: "Gestión de reincidentes",
  },
  {
    id: "fatigue-sensor",
    name: "Fatiga y somnolencia por sensor",
    technicalName: "Fatigue And Drowsiness Sensor",
    family: 0,
    risk: "Riesgo crítico de accidente por microsueño y fatiga en cabina.",
    entities: ["Conductor", "Turno", "Jornada", "Ruta", "Cámara/Sensor"],
    evidence: [
      "Sensor de cabina",
      "Video/fotograma",
      "Hora local",
      "Descanso previo",
      "Historial",
    ],
    kpiChip: "Episodios / jornada",
    see: "Detecta señal de fatiga o somnolencia mediante sensor o cámara en cabina.",
    understand:
      "Cruza jornada, conductor, hora, ruta, historial y descanso previo.",
    act: "Alerta inmediata, contacto y detención segura si aplica.",
    solve:
      "Gestión de fatiga, planificación de jornadas, descansos y capacitación.",
    improve: "Reduce episodios y correlaciona con jornadas y turnos críticos.",
    kpis: [
      "Episodios por jornada",
      "Correlación con turno",
      "Reincidencia",
      "Reducción mensual",
    ],
    q: "¿Atendemos el episodio o rediseñamos las jornadas que producen la fatiga?",
    story:
      "La fatiga por sensor es señal crítica: pocos eventos, altísimo costo si se ignora.",
    owner: "Planificación de jornadas",
    action: "Rediseño de turnos + descanso",
  },
  {
    id: "fatigue-event",
    name: "Fatiga y somnolencia por evento",
    technicalName: "Fatigue And Drowsiness",
    family: 0,
    risk: "Riesgo de accidente por fatiga; incumplimiento de descanso.",
    entities: ["Conductor", "Jornada", "Ruta", "Turno", "Descanso"],
    evidence: [
      "Evento registrado",
      "Hora local",
      "Descanso previo",
      "Historial",
    ],
    kpiChip: "Eventos por turno",
    see: "Registra un evento de fatiga o somnolencia asociado al conductor.",
    understand:
      "Analiza origen del evento, conductor, jornada, ruta y descansos.",
    act: "Contacto inmediato y activación del protocolo de seguridad.",
    solve: "Rediseña jornadas y controles preventivos de fatiga.",
    improve: "Reduce eventos y mejora el cumplimiento de descanso.",
    kpis: [
      "Eventos por turno",
      "Cumplimiento de descanso",
      "Reincidencia",
      "Reducción mensual",
    ],
    q: "¿La fatiga es del conductor o del calendario que le asignamos?",
    story:
      "La fatiga registrada por evento cierra el círculo con la planificación de jornadas.",
    owner: "Planificación de jornadas",
    action: "Controles preventivos de fatiga",
  },
  {
    id: "double-driver",
    name: "Rotación de doble conductor",
    technicalName: "Double Driver Rotation Check",
    family: 0,
    risk: "Fatiga en rutas largas por rotación mal ejecutada; incumplimiento operacional.",
    entities: ["Conductores", "Ruta", "Jornada", "Plan", "Tiempos de descanso"],
    evidence: [
      "Cambios de conductor",
      "Tiempos de conducción",
      "GPS",
      "Timestamp",
    ],
    kpiChip: "Cumplimiento rotación",
    see: "Detecta incumplimiento o anomalía en la rotación de doble conductor.",
    understand: "Cruza ruta, jornada, conductores, plan y tiempos de descanso.",
    act: "Notifica y valida la rotación en curso.",
    solve: "Ajusta la planificación y la asignación de tripulación.",
    improve: "Aumenta el cumplimiento de rotación y reduce la fatiga.",
    kpis: [
      "% cumplimiento de rotación",
      "Fatiga asociada",
      "Reincidencia por ruta",
      "Reducción mensual",
    ],
    q: "¿La rotación falla por disciplina o porque el plan no la hace posible?",
    story:
      "La rotación de doble conductor solo funciona si el plan la hace posible; si no, la fatiga vuelve.",
    owner: "Transportista · protocolo",
    action: "Ajuste de asignación de tripulación",
  },
  {
    id: "risk-zone-stop",
    name: "Detención en zona de riesgo",
    technicalName: "Risk Zone Stop",
    family: 1,
    risk: "Robo, riesgo de carga y exposición patrimonial.",
    entities: ["Vehículo", "Conductor", "Ruta", "Zona", "Geocerca", "Servicio"],
    evidence: [
      "Estado detenido",
      "Geocerca de riesgo",
      "Duración",
      "GPS",
      "Historial de zona",
    ],
    kpiChip: "Detenciones no planif.",
    see: "Detecta un activo detenido dentro de una zona marcada como riesgo.",
    understand:
      "Cruza duración, causa aparente, ruta, conductor e historial de la zona.",
    act: "Contacto inmediato, escalamiento y seguimiento hasta reanudar.",
    solve:
      "Rediseño de ruta, definición de zonas seguras y protocolos de parada.",
    improve: "Reduce detenciones no planificadas en zonas críticas.",
    kpis: [
      "Detenciones no planificadas",
      "Duración media en zona",
      "Reincidencia por ruta",
      "Reducción mensual",
    ],
    q: "¿La parada es evitable con una zona segura al alcance en el plan de ruta?",
    story:
      "Una detención en zona de riesgo es exposición patrimonial. La recurrencia por ruta dice dónde faltan zonas seguras.",
    owner: "Planificación + Seguridad",
    action: "Zonas seguras planificadas en ruta",
  },
  {
    id: "night-risk-stay",
    name: "Pernoctación en zona de riesgo",
    technicalName: "Night Risk Stay",
    family: 1,
    risk: "Exposición nocturna de la carga e incidentes patrimoniales.",
    entities: [
      "Vehículo",
      "Conductor",
      "Zona",
      "Geocerca",
      "Servicio",
      "Planificación",
    ],
    evidence: [
      "Permanencia nocturna",
      "Geocerca de riesgo",
      "Hora",
      "GPS",
      "Estacionamiento disponible",
    ],
    kpiChip: "Pernoctaciones riesgo",
    see: "Detecta permanencia nocturna dentro de una zona de riesgo.",
    understand:
      "Analiza causa, planificación y disponibilidad de estacionamiento seguro.",
    act: "Escala a seguridad/operaciones y confirma la condición del activo.",
    solve:
      "Define zonas autorizadas y rutas con puntos seguros de pernoctación.",
    improve: "Reduce las pernoctaciones riesgosas.",
    kpis: [
      "Pernoctaciones en riesgo",
      "% con zona segura al alcance",
      "Reincidencia por corredor",
      "Reducción mensual",
    ],
    q: "¿Existe un punto seguro planificado donde el viaje obliga a pernoctar?",
    story:
      "La pernoctación en zona de riesgo es evitable cuando el plan define dónde parar.",
    owner: "Planificación",
    action: "Puntos seguros de pernoctación",
  },
  {
    id: "no-auth-zone",
    name: "Pernoctación en zona no autorizada",
    technicalName: "No Authorized Zone Stop",
    family: 1,
    risk: "Riesgo patrimonial e incumplimiento del estándar de paradas de ruta.",
    entities: [
      "Vehículo",
      "Conductor",
      "Ruta",
      "Zona autorizada",
      "Planificación",
    ],
    evidence: [
      "Permanencia nocturna",
      "Fuera de zona autorizada",
      "GPS",
      "Timestamp",
    ],
    kpiChip: "Pernoct. fuera estándar",
    see: "Detecta permanencia nocturna en una zona no autorizada.",
    understand:
      "Analiza causa, conductor, planificación y alternativas disponibles en ruta.",
    act: "Escala y confirma el estado del activo y la carga.",
    solve:
      "Define paradas autorizadas y controles preventivos donde el límite de manejo obliga a parar.",
    improve: "Reduce las pernoctaciones fuera de estándar.",
    kpis: [
      "Pernoctaciones fuera de estándar",
      "Cobertura de zonas autorizadas",
      "Reincidencia",
      "Reducción mensual",
    ],
    q: "¿Hay una zona autorizada al alcance del punto donde el conductor debe parar?",
    story:
      "La pernoctación fuera de zona autorizada aparece cuando el límite de manejo obliga a parar y no hay zona al alcance.",
    owner: "Planificación",
    action: "Dotar zonas autorizadas en ruta",
  },
  {
    id: "restricted-area",
    name: "Cruce en área no permitida",
    technicalName: "Restricted Area Crossing",
    family: 1,
    risk: "Incumplimiento geográfico, riesgo de seguridad interna y de control.",
    entities: [
      "Conductor",
      "Ruta",
      "Geocerca",
      "Zona restringida",
      "Autorización",
    ],
    evidence: [
      "Ingreso/cruce de geocerca",
      "GPS",
      "Timestamp",
      "Autorización",
      "Señalización",
    ],
    kpiChip: "Cruces por zona",
    see: "Detecta el ingreso o cruce por una zona restringida.",
    understand: "Cruza conductor, ruta, señalización, autorización y geocerca.",
    act: "Notifica la desviación y confirma el motivo del cruce.",
    solve: "Corrige la ruta, la señalización o los permisos según la causa.",
    improve: "Reduce los cruces no autorizados por zona.",
    kpis: [
      "Cruces no autorizados",
      "Reincidencia por ruta",
      "% con permiso válido",
      "Reducción mensual",
    ],
    q: "¿El cruce es error del conductor o una ruta mal trazada que lo induce?",
    story:
      "El cruce restringido suele ser una ruta mal trazada más que un error del conductor.",
    owner: "Planificación de ruta",
    action: "Corrección de ruta y permisos",
  },
  {
    id: "near-border",
    name: "Proximidad a paso fronterizo",
    technicalName: "Near Border Crossing",
    family: 1,
    risk: "Riesgo patrimonial y de control en operaciones internacionales.",
    entities: [
      "Vehículo",
      "Ruta autorizada",
      "Servicio",
      "Carga",
      "Documentación",
      "Destino",
    ],
    evidence: [
      "Cercanía a geocerca fronteriza",
      "GPS",
      "Ruta autorizada",
      "Documentación",
    ],
    kpiChip: "Aproximaciones",
    see: "Detecta un activo próximo a un paso fronterizo.",
    understand:
      "Cruza ruta autorizada, servicio, carga, documentación y destino.",
    act: "Valida la autorización y la trazabilidad del movimiento.",
    solve: "Fortalece controles de ruta y de documentación asociada.",
    improve: "Reduce las aproximaciones no justificadas.",
    kpis: [
      "Aproximaciones no justificadas",
      "% con documentación válida",
      "Reincidencia",
      "Reducción mensual",
    ],
    q: "¿La aproximación está autorizada y documentada, o es una desviación de ruta?",
    story:
      "La proximidad fronteriza exige validar autorización y trazabilidad al instante.",
    owner: "Control de ruta",
    action: "Controles de ruta y documentación",
  },
  {
    id: "off-hours",
    name: "Movimiento en horario no permitido",
    technicalName: "Off Hours Driving",
    family: 1,
    risk: "Riesgo nocturno, incumplimiento de control horario y exposición operacional.",
    entities: [
      "Vehículo",
      "Conductor",
      "Ventana horaria",
      "Zona",
      "Servicio",
      "Planificación",
    ],
    evidence: [
      "Movimiento en ventana no autorizada",
      "Hora local",
      "GPS",
      "Autorización",
    ],
    kpiChip: "Cumplimiento horario",
    see: "Detecta movimiento fuera de la ventana horaria autorizada.",
    understand:
      "Cruza tipo de operación, urgencia, autorización, zona y conductor.",
    act: "Valida la autorización o detiene la operación según protocolo.",
    solve:
      "Revisa la planificación, los permisos y los controles preventivos de despacho.",
    improve:
      "Reduce los movimientos no autorizados y aumenta el cumplimiento horario.",
    kpis: [
      "Movimientos no autorizados",
      "Eventos por ruta",
      "% viajes dentro de ventana",
      "Reducción mensual",
    ],
    q: "¿El conductor decide moverse de noche o el despacho lo mete a la ventana prohibida?",
    story:
      "El movimiento en horario prohibido rara vez lo decide el conductor: el despacho lo mete a la ventana.",
    owner: "Planificación · ventana de despacho",
    action: "Reajuste de ventana de despacho",
  },
  {
    id: "check-engine",
    name: "Check Engine / falla de motor",
    technicalName: "Check Engine",
    family: 2,
    risk: "Detención en ruta y falla mecánica mayor.",
    entities: ["Vehículo", "Motor", "Historial", "Ruta", "Mantenimiento"],
    evidence: [
      "Código DTC",
      "Telemetría de motor",
      "Severidad",
      "Timestamp",
      "Historial",
    ],
    kpiChip: "Fallas en ruta",
    see: "Detecta una alerta de motor activa (código de falla).",
    understand:
      "Cruza código, severidad, historial, ruta y criticidad del servicio.",
    act: "Escala a mantenimiento y define la continuidad del viaje.",
    solve: "Diagnóstico e intervención según el código y su recurrencia.",
    improve: "Reduce fallas en ruta y mejora la programación de mantenimiento.",
    kpis: [
      "Fallas en ruta",
      "Reincidencia por vehículo",
      "Tiempo a intervención",
      "Reducción mensual",
    ],
    q: "¿Reaccionamos a la falla o anticipamos el patrón por marca/modelo?",
    story:
      "El Check Engine anticipa la detención en ruta si se lee el patrón por marca/modelo.",
    owner: "Mantención",
    action: "De reactivo a preventivo",
  },
  {
    id: "battery-low",
    name: "Batería baja",
    technicalName: "Battery Low",
    family: 2,
    risk: "Panne por batería, pérdida de continuidad y de trazabilidad.",
    entities: ["Vehículo", "Batería", "Uso", "Ruta", "Historial"],
    evidence: [
      "Nivel de batería",
      "Telemetría eléctrica",
      "Timestamp",
      "Historial",
    ],
    kpiChip: "Fallas por batería",
    see: "Detecta un nivel de batería bajo sobre umbral.",
    understand:
      "Cruza vehículo, uso, historial, ruta y criticidad del servicio.",
    act: "Alerta a mantenimiento y define la prioridad de intervención.",
    solve: "Intervención preventiva antes de la panne.",
    improve: "Reduce fallas por batería y asistencias en ruta.",
    kpis: [
      "Fallas por batería",
      "Asistencias en ruta",
      "Reincidencia por vehículo",
      "Reducción mensual",
    ],
    q: "¿Cambiamos la batería cuando falla o cuando el patrón lo anticipa?",
    story: "La batería baja se cambia mejor por patrón que por panne.",
    owner: "Mantención",
    action: "Intervención preventiva",
  },
  {
    id: "charging-failure",
    name: "Falla de carga de batería",
    technicalName: "Charging Failure",
    family: 2,
    risk: "Falla eléctrica progresiva y detención en ruta.",
    entities: ["Vehículo", "Alternador", "Batería", "Historial", "Ruta"],
    evidence: ["Telemetría de carga", "Voltaje", "Timestamp", "Historial"],
    kpiChip: "Detenciones eléctricas",
    see: "Detecta una falla en el sistema de carga.",
    understand:
      "Cruza vehículo, alternador, batería, historial y criticidad de la ruta.",
    act: "Alerta a mantenimiento y evalúa la continuidad del servicio.",
    solve: "Intervención preventiva del sistema de carga.",
    improve: "Reduce detenciones por falla eléctrica.",
    kpis: [
      "Detenciones por falla eléctrica",
      "Tiempo a intervención",
      "Reincidencia",
      "Reducción mensual",
    ],
    q: "¿La falla eléctrica se atiende antes de dejar el camión detenido en ruta?",
    story: "La falla de carga avisa antes de dejar el camión detenido.",
    owner: "Mantención",
    action: "Intervención del sistema de carga",
  },
  {
    id: "engine-overheat",
    name: "Sobrecalentamiento del motor",
    technicalName: "Engine Overheat",
    family: 2,
    risk: "Daño mecánico mayor y pérdida de continuidad operacional.",
    entities: [
      "Vehículo",
      "Motor",
      "Carga",
      "Ruta",
      "Pendiente",
      "Mantenimiento",
    ],
    evidence: [
      "Temperatura de refrigerante",
      "Telemetría",
      "Timestamp",
      "Historial",
    ],
    kpiChip: "Eventos térmicos",
    see: "Detecta temperatura de motor sobre el umbral seguro.",
    understand:
      "Cruza vehículo, carga, ruta, pendiente, historial y mantenimiento.",
    act: "Alerta, detiene si aplica y escala a mantenimiento.",
    solve: "Diagnóstico preventivo y ajuste del plan de mantenimiento.",
    improve: "Reduce eventos térmicos y fallas mecánicas mayores.",
    kpis: [
      "Eventos térmicos",
      "Fallas mecánicas mayores",
      "Reincidencia por vehículo",
      "Reducción mensual",
    ],
    q: "¿El sobrecalentamiento es de mantenimiento o de una ruta/carga mal asignada?",
    story: "El sobrecalentamiento cruza mantención con ruta y carga asignada.",
    owner: "Mantención",
    action: "Diagnóstico preventivo",
  },
  {
    id: "vehicle-maintenance",
    name: "Mantenimiento de vehículo",
    technicalName: "Vehicle Maintenance",
    family: 2,
    risk: "Falla en ruta por vencimiento de mantención no tratado.",
    entities: [
      "Vehículo",
      "Kilometraje",
      "Contrato",
      "Disponibilidad",
      "Historial",
    ],
    evidence: ["Km/uso", "Vencimiento de pauta", "Historial", "Criticidad"],
    kpiChip: "Vencimientos no tratados",
    see: "Detecta una condición o vencimiento asociado a mantenimiento.",
    understand:
      "Cruza km, uso, historial, criticidad, contrato y disponibilidad de flota.",
    act: "Programa la intervención o alerta al responsable.",
    solve: "Pasa de mantenimiento reactivo a preventivo/predictivo.",
    improve: "Reduce fallas en ruta y vencimientos no tratados.",
    kpis: [
      "Vencimientos no tratados",
      "Fallas en ruta",
      "% preventivo vs reactivo",
      "Reducción mensual",
    ],
    q: "¿La flota se mantiene por calendario o por condición real de uso?",
    story: "El mantenimiento por condición de uso reduce las fallas en ruta.",
    owner: "Mantención",
    action: "Preventivo/predictivo por uso",
  },
  {
    id: "lost-signal",
    name: "Pérdida de señal",
    technicalName: "Lost Signal",
    family: 2,
    risk: "Ceguera operacional, pérdida de trazabilidad y calidad de proveedor GPS.",
    entities: ["Vehículo", "Proveedor GPS", "Zona", "Ruta", "Cobertura"],
    evidence: [
      "Ausencia de señal",
      "Última posición",
      "Duración sin señal",
      "Historial de zona",
    ],
    kpiChip: "Minutos sin trazabilidad",
    see: "Detecta pérdida de transmisión o ausencia de la señal esperada.",
    understand:
      "Cruza proveedor, zona, activo, ruta, recurrencia, horario y cobertura.",
    act: "Escala a torre/proveedor, confirma condición del activo y registra la ventana sin trazabilidad.",
    solve:
      "Identifica si la causa es cobertura, hardware, energía, integración o proveedor.",
    improve:
      "Reduce zonas ciegas, exige SLA de señal y mantiene un ranking de proveedores GPS.",
    kpis: [
      "Minutos sin trazabilidad por viaje",
      "Zonas ciegas recurrentes",
      "SLA de señal por proveedor",
      "Reducción mensual",
    ],
    q: "¿Perdemos señal por geografía o por un proveedor que no cumple su SLA?",
    story:
      "La pérdida de señal fue el segundo síntoma del mes. Separar geografía de proveedor es la clave para reducir zonas ciegas.",
    owner: "Proveedor GPS",
    action: "SLA de señal + ranking de proveedores",
  },
  {
    id: "engine-idle",
    name: "Ralentí del motor",
    technicalName: "Engine Idle",
    family: 3,
    risk: "Consumo improductivo de combustible y emisiones.",
    entities: [
      "Vehículo",
      "Conductor",
      "Zona",
      "Espera operacional",
      "Carga/Descarga",
    ],
    evidence: [
      "Motor encendido sin movimiento",
      "Duración",
      "GPS",
      "Timestamp",
      "Clima",
    ],
    kpiChip: "Ralentí improductivo",
    see: "Detecta motor encendido sin movimiento sobre umbral de tiempo.",
    understand:
      "Cruza zona, conductor, espera operacional, clima y actividad de carga/descarga.",
    act: "Notifica o registra la condición de ralentí.",
    solve: "Separa el ralentí justificado del hábito operacional.",
    improve: "Reduce el consumo improductivo y las emisiones.",
    kpis: [
      "Horas de ralentí",
      "Litros improductivos",
      "Reincidencia por conductor",
      "Reducción mensual",
    ],
    q: "¿El ralentí es una espera necesaria o un hábito que cuesta combustible?",
    story:
      "El ralentí separa la espera necesaria del hábito que cuesta combustible.",
    owner: "Operación",
    action: "Gestión de hábito de ralentí",
  },
  {
    id: "eta-early",
    name: "Desvío anticipado de ETA",
    technicalName: "Deviation_Eta_Early",
    family: 3,
    risk: "Congestión en recepción e incumplimiento de ventana por adelanto.",
    entities: ["Servicio", "Ruta", "Ventana", "Bodega", "Cliente", "Destino"],
    evidence: [
      "ETA proyectado vs plan",
      "GPS",
      "Timestamp",
      "Ventana de recepción",
    ],
    kpiChip: "Desvío de ventana",
    see: "Detecta una llegada proyectada antes de lo planificado.",
    understand: "Analiza el impacto en recepción, ventana, bodega y cliente.",
    act: "Coordina la reprogramación o el ajuste de la recepción.",
    solve: "Mejora la calidad de la planificación y del cálculo de ETA.",
    improve: "Reduce las desviaciones de ventana.",
    kpis: [
      "Desviaciones de ventana",
      "Precisión de ETA",
      "Congestión en recepción",
      "Reducción mensual",
    ],
    q: "¿El adelanto ayuda o genera congestión que la bodega no puede absorber?",
    story:
      "El adelanto de ETA puede ayudar o congestionar la recepción. Depende de la calidad del plan.",
    owner: "Planificación",
    action: "Recalibrar ETA + coordinar recepción",
  },
  {
    id: "eta-late",
    name: "Desvío retardado de ETA",
    technicalName: "Deviation_Eta_Late",
    family: 3,
    risk: "Incumplimiento de SLA y atrasos recurrentes.",
    entities: ["Servicio", "Ruta", "Espera", "Origen", "Destino", "Cliente"],
    evidence: [
      "ETA proyectado vs plan",
      "GPS",
      "Timestamp",
      "Tráfico",
      "Esperas",
    ],
    kpiChip: "Cumplimiento SLA",
    see: "Detecta una llegada proyectada posterior a lo planificado.",
    understand:
      "Analiza la causa probable, ruta, esperas, tráfico, origen y destino.",
    act: "Notifica el atraso, coordina la recepción y actualiza el ETA.",
    solve: "Ajusta planificación, capacidad, ventanas y rutas.",
    improve: "Reduce atrasos recurrentes y mejora la precisión del ETA.",
    kpis: [
      "% cumplimiento SLA",
      "Atrasos recurrentes",
      "Precisión de ETA",
      "Reducción mensual",
    ],
    q: "¿El atraso es puntual o un cuello de botella estructural de la ruta?",
    story:
      "El atraso de ETA distingue lo puntual del cuello de botella estructural de la ruta.",
    owner: "Planificación",
    action: "Recalibrar ETA + capacidad",
  },
  {
    id: "atraso-plan",
    name: "Atraso de plan",
    technicalName: "Atraso de Plan",
    family: 3,
    risk: "Incumplimiento operacional, impacto en SLA y en el cliente.",
    entities: [
      "Servicio",
      "Etapa",
      "Responsable",
      "Ruta",
      "Proveedor",
      "Cliente",
    ],
    evidence: [
      "Desviación negativa vs plan",
      "Hitos por geocerca",
      "Timestamp",
      "Etapa",
    ],
    kpiChip: "Atraso por etapa",
    see: "Detecta una desviación negativa contra el plan de la operación.",
    understand:
      "Cruza etapa, causa probable, responsable e impacto en el cliente.",
    act: "Escala, replanifica y comunica el atraso.",
    solve: "Identifica el cuello de botella recurrente por etapa.",
    improve: "Reduce atrasos estructurales por etapa, ruta o proveedor.",
    kpis: [
      "Atraso medio por etapa",
      "Cuellos de botella recurrentes",
      "% servicios en plan",
      "Reducción mensual",
    ],
    q: "¿El atraso vive en una etapa específica que podemos rediseñar?",
    story:
      "El atraso de plan vive en una etapa: identificarla es el primer paso para rediseñarla.",
    owner: "Planificación",
    action: "Rediseño de la etapa cuello de botella",
  },
  {
    id: "adelanto-plan",
    name: "Adelanto de plan",
    technicalName: "Adelanto de Plan",
    family: 3,
    risk: "Congestión en recepción y desincronización con bodega/cliente.",
    entities: ["Servicio", "Etapa", "Ventana", "Bodega", "Capacidad"],
    evidence: [
      "Desviación positiva vs plan",
      "Hitos por geocerca",
      "Timestamp",
    ],
    kpiChip: "Variabilidad vs plan",
    see: "Detecta una operación adelantada respecto al plan.",
    understand: "Analiza el impacto en recepción, capacidad y ventanas.",
    act: "Coordina el ajuste y evita congestión aguas abajo.",
    solve: "Mejora la precisión de la planificación.",
    improve: "Reduce la variabilidad contra el plan.",
    kpis: [
      "Variabilidad vs plan",
      "Congestión en recepción",
      "Precisión de planificación",
      "Reducción mensual",
    ],
    q: "¿Adelantar suma capacidad o solo mueve el cuello de botella?",
    story:
      "El adelanto de plan mueve el cuello de botella si no se coordina aguas abajo.",
    owner: "Planificación",
    action: "Coordinación de capacidad",
  },
  {
    id: "sobre-estadia",
    name: "Sobre-estadía en origen/destino",
    technicalName: "Sobre-estadía en Origen/Destino",
    family: 3,
    risk: "Costos ocultos, baja productividad y saturación de patio/bodega.",
    entities: [
      "Servicio",
      "Etapa",
      "Recurso",
      "Ventana",
      "Congestión",
      "Documentación",
    ],
    evidence: [
      "Permanencia > estándar",
      "Hitos por geocerca",
      "Timestamp",
      "Ventana",
    ],
    kpiChip: "Tiempo de permanencia",
    see: "Detecta permanencia superior al estándar en origen o destino.",
    understand:
      "Cruza causa, etapa, recurso, ventana, congestión y documentación.",
    act: "Escala y destraba el proceso detenido.",
    solve: "Rediseña agenda, capacidad, documentación o prioridad de atención.",
    improve: "Reduce el tiempo medio de permanencia y los costos asociados.",
    kpis: [
      "Tiempo medio de permanencia",
      "Costo por sobre-estadía",
      "Reincidencia por sitio",
      "Reducción mensual",
    ],
    q: "¿La sobre-estadía es del transportista o de la bodega que no lo recibe a tiempo?",
    story:
      "La sobre-estadía suele ser de la bodega que no recibe a tiempo, no del transportista.",
    owner: "Coordinación + bodega",
    action: "Reagenda de citas y prioridad",
  },
  {
    id: "control-geocercas",
    name: "Control de proceso por geocercas",
    technicalName: "Control de Proceso por Geocercas",
    family: 3,
    risk: "Pérdida de trazabilidad de proceso y fricción operacional.",
    entities: [
      "Servicio",
      "Hito operacional",
      "Secuencia",
      "Geocerca",
      "Responsable",
    ],
    evidence: [
      "Entrada/salida/permanencia en geocerca",
      "Secuencia",
      "Timestamp",
    ],
    kpiChip: "Cumplimiento secuencia",
    see: "Detecta entrada, salida o permanencia en geocercas relevantes del proceso.",
    understand:
      "Cruza el hito operacional, la secuencia, el tiempo, la desviación y el responsable.",
    act: "Gatilla tareas, confirmaciones o alertas según el hito.",
    solve: "Corrige el flujo real frente al flujo definido.",
    improve:
      "Aumenta el cumplimiento de secuencia y reduce la fricción operacional.",
    kpis: [
      "% cumplimiento de secuencia",
      "Desviaciones de flujo",
      "Tiempo por hito",
      "Reducción mensual",
    ],
    q: "¿El flujo real sigue el proceso definido o lo estamos descubriendo desviado?",
    story:
      "El control por geocercas revela el flujo real frente al proceso definido.",
    owner: "Coordinación",
    action: "Corrección de flujo operacional",
  },
  {
    id: "epp",
    name: "Uso de EPP",
    technicalName: "Missing Protective Equipment",
    family: 4,
    risk: "Riesgo a las personas e incumplimiento HSE.",
    entities: [
      "Operador",
      "Rol",
      "Turno",
      "Proveedor",
      "Zona",
      "Tipo de tarea",
    ],
    evidence: [
      "Detección visual",
      "Cámara",
      "Fotograma",
      "Timestamp",
      "Ubicación",
    ],
    kpiChip: "Cumplimiento EPP",
    see: "Detecta ausencia o incumplimiento del EPP requerido.",
    understand: "Cruza ubicación, rol, turno, proveedor y tipo de tarea.",
    act: "Detiene la actividad, notifica al supervisor y registra la evidencia.",
    solve: "Capacitación, control de acceso y checklist previo a la tarea.",
    improve:
      "Aumenta el cumplimiento de EPP y reduce la reincidencia por equipo/proveedor.",
    kpis: [
      "% cumplimiento EPP",
      "Reincidencia por proveedor",
      "Incidentes HSE",
      "Reducción mensual",
    ],
    q: "¿El incumplimiento es individual o falla el control de acceso a la faena?",
    story:
      "El incumplimiento de EPP se corrige mejor en el control de acceso que en el individuo.",
    owner: "HSE",
    action: "Control de acceso + checklist",
  },
  {
    id: "load-securing-absence",
    name: "Ausencia de amarre y sujeción",
    technicalName: "Check Load Securing Absence",
    family: 4,
    risk: "Accidente por carga suelta e incumplimiento documental/visual.",
    entities: [
      "Operador",
      "Transportista",
      "Origen",
      "Tipo de carga",
      "Procedimiento",
    ],
    evidence: ["Evidencia visual", "Cámara/foto", "Checklist", "Timestamp"],
    kpiChip: "Salidas sin evidencia",
    see: "Detecta carga sin evidencia de amarre o sujeción.",
    understand:
      "Cruza tipo de carga, operador, origen, transportista y procedimiento.",
    act: "Bloquea la salida o solicita corrección y evidencia.",
    solve: "Estandariza el checklist y la responsabilidad antes de la salida.",
    improve: "Reduce las salidas con evidencia incompleta o inexistente.",
    kpis: [
      "Salidas sin evidencia",
      "Reincidencia por origen",
      "% con checklist",
      "Reducción mensual",
    ],
    q: "¿Falta el amarre o falta el control que lo verifica antes de salir?",
    story:
      "La ausencia de amarre no es solo falta del operador: es falta del control que lo verifica.",
    owner: "HSE",
    action: "Checklist obligatorio pre-salida",
  },
  {
    id: "load-securing-deficient",
    name: "Amarre y sujeción deficiente",
    technicalName: "Deficient Load Securing",
    family: 4,
    risk: "Riesgo en ruta por sujeción incorrecta y daño de carga.",
    entities: [
      "Operador",
      "Transportista",
      "Origen",
      "Tipo de carga",
      "Patrón de falla",
    ],
    evidence: ["Evidencia visual", "Cámara/foto", "Timestamp", "Historial"],
    kpiChip: "Reincidencia amarre",
    see: "Detecta evidencia de amarre insuficiente o incorrecto.",
    understand:
      "Cruza tipo de carga, operador, transportista, origen y patrón de falla.",
    act: "Corrige antes de la salida o registra la desviación.",
    solve: "Ajusta procedimiento, capacitación y control de calidad.",
    improve: "Reduce la reincidencia por origen, operador o transportista.",
    kpis: [
      "Reincidencia por operador",
      "% amarres correctos",
      "Daños de carga",
      "Reducción mensual",
    ],
    q: "¿Es una falla puntual o un origen/operador que repite el error?",
    story:
      "El amarre deficiente repite por origen/operador: ahí está la palanca.",
    owner: "HSE",
    action: "Procedimiento + control de calidad",
  },
  {
    id: "man-machine",
    name: "Hombre–Máquina",
    technicalName: "Man Machine",
    family: 4,
    risk: "Accidente grave por interacción riesgosa persona-equipo.",
    entities: ["Operador", "Zona", "Turno", "Flujo peatonal", "Layout"],
    evidence: ["Detección de proximidad", "Cámara/sensor", "Timestamp", "Zona"],
    kpiChip: "Interacciones riesgosas",
    see: "Detecta proximidad o interacción riesgosa entre persona y máquina.",
    understand:
      "Cruza zona, turno, operador, flujo peatonal y diseño del layout.",
    act: "Alerta inmediata, detención o advertencia.",
    solve: "Rediseño de segregación, flujos y señalización.",
    improve: "Reduce las interacciones riesgosas por zona y turno.",
    kpis: [
      "Interacciones riesgosas",
      "Reincidencia por zona",
      "Cuasi-accidentes",
      "Reducción mensual",
    ],
    q: "¿Corregimos conductas o rediseñamos el layout que las hace posibles?",
    story:
      "La interacción hombre-máquina se ataca rediseñando el layout, no solo la conducta.",
    owner: "HSE",
    action: "Rediseño de segregación y flujos",
  },
  {
    id: "assistance",
    name: "Asistencia en ruta",
    technicalName: "Assistance Button",
    family: 4,
    risk: "Interrupción de servicio y conductor sin soporte oportuno.",
    entities: [
      "Conductor",
      "Ubicación",
      "Tipo de problema",
      "Ruta",
      "Servicio",
    ],
    evidence: ["Solicitud activa", "GPS", "Tipo de problema", "Timestamp"],
    kpiChip: "Tiempo de respuesta",
    see: "Detecta una solicitud activa de asistencia.",
    understand:
      "Cruza ubicación, tipo de problema, criticidad, ruta y servicio.",
    act: "Contacta, deriva, escala y cierra con resultado registrado.",
    solve: "Identifica los tipos recurrentes de asistencia.",
    improve:
      "Reduce las causas frecuentes de asistencia y los tiempos de respuesta.",
    kpis: [
      "Tiempo de respuesta",
      "Asistencias por 100 viajes",
      "Tipos recurrentes",
      "Reducción mensual",
    ],
    q: "¿Atendemos cada asistencia o eliminamos la causa que las repite?",
    story:
      "Cada asistencia es una causa que, si se repite, conviene eliminar en la fuente.",
    owner: "Torre de control",
    action: "Eliminar causas recurrentes",
  },
  {
    id: "sos",
    name: "Botón de pánico",
    technicalName: "Sos Button",
    family: 4,
    risk: "Emergencia y riesgo crítico a la seguridad personal.",
    entities: ["Conductor", "Ubicación", "Contexto", "Riesgo", "Historial"],
    evidence: ["Activación SOS", "GPS", "Timestamp", "Contexto de zona"],
    kpiChip: "Respuesta a emergencia",
    see: "Detecta la activación del botón SOS.",
    understand:
      "Cruza ubicación, conductor, contexto, riesgo e historial de la zona.",
    act: "Activa el protocolo crítico inmediato, escala y registra evidencia.",
    solve: "Análisis post incidente y definición de controles preventivos.",
    improve: "Reduce la exposición y mejora la respuesta ante emergencias.",
    kpis: [
      "Tiempo de respuesta a SOS",
      "Exposición por zona",
      "Incidentes",
      "Reducción mensual",
    ],
    q: "¿Respondemos bien a la emergencia y reducimos la exposición que la provoca?",
    story:
      "El SOS es el evento crítico: la reunión debe mostrar respuesta y reducción de exposición.",
    owner: "Torre de control",
    action: "Protocolo crítico + prevención",
  },
  {
    id: "gps-providers",
    name: "Confiabilidad de proveedores GPS",
    technicalName: "Puntualidad y cobertura por proveedor",
    family: 5,
    special: "gps",
    risk: "Ceguera operacional y baja trazabilidad cuando la señal del proveedor llega tarde o con cortes.",
    entities: [
      "Proveedor GPS",
      "Dispositivos",
      "Señal",
      "Puntualidad",
      "Confiabilidad",
    ],
    story: "Antes de hablar de síntomas, hay que confiar en la señal.",
    owner: "Gestión de flota / proveedor",
    action: "SLA de señal + ranking de proveedores",
  },
];

export const META = {
  month: "Junio 2026",
  period: "2026-06-01 → 2026-06-30",
  total_trips: 3000,
  source: "operación real de transporte · junio 2026",
  symptomsWithData: [
    "Continuous Drive Check",
    "Continuous Resting Check",
    "Deviation_Eta_Early",
    "Deviation_Eta_Late",
    "Double Driver Rotation Check",
    "Fatigue And Drowsiness Sensor",
    "Lost Signal",
    "No Authorized Zone Stop",
    "Off Hours Driving",
    "Risk Zone Stop",
    "Sos Button",
    "Speed Limit Standard",
  ],
};

export const PRODDATA: Record<string, ProdEntry> = {
  "Continuous Drive Check": {
    kpis: {
      total: 4204,
      viajes: 620,
      conductores: 254,
      transportistas: 61,
      gestionables: 2190,
      con_tratamiento: 1916,
      validos: 397,
      invalidados: 1519,
      icu1: 1138,
      icu2: 876,
      icu3: 897,
      icu4: 1293,
      blackcode: 1293,
      sla_p50_min: 120.13,
      sla_p90_min: 120.87,
      trat_5min: 25,
      trat_2h: 870,
    },
    daily: [
      { dia: "2026-06-01", total: 65, icu4: 13, gestionables: 26, validos: 7 },
      {
        dia: "2026-06-02",
        total: 137,
        icu4: 34,
        gestionables: 63,
        validos: 12,
      },
      {
        dia: "2026-06-03",
        total: 162,
        icu4: 45,
        gestionables: 78,
        validos: 18,
      },
      { dia: "2026-06-04", total: 156, icu4: 34, gestionables: 68, validos: 6 },
      {
        dia: "2026-06-05",
        total: 141,
        icu4: 53,
        gestionables: 79,
        validos: 12,
      },
      {
        dia: "2026-06-06",
        total: 208,
        icu4: 113,
        gestionables: 139,
        validos: 31,
      },
      { dia: "2026-06-07", total: 139, icu4: 34, gestionables: 69, validos: 5 },
      { dia: "2026-06-08", total: 129, icu4: 27, gestionables: 63, validos: 6 },
      {
        dia: "2026-06-09",
        total: 203,
        icu4: 54,
        gestionables: 102,
        validos: 25,
      },
      {
        dia: "2026-06-10",
        total: 132,
        icu4: 35,
        gestionables: 66,
        validos: 11,
      },
      { dia: "2026-06-11", total: 87, icu4: 28, gestionables: 43, validos: 5 },
      {
        dia: "2026-06-12",
        total: 135,
        icu4: 54,
        gestionables: 78,
        validos: 21,
      },
      {
        dia: "2026-06-13",
        total: 264,
        icu4: 118,
        gestionables: 170,
        validos: 26,
      },
      {
        dia: "2026-06-14",
        total: 161,
        icu4: 67,
        gestionables: 90,
        validos: 12,
      },
      { dia: "2026-06-15", total: 98, icu4: 19, gestionables: 40, validos: 8 },
      {
        dia: "2026-06-16",
        total: 238,
        icu4: 66,
        gestionables: 128,
        validos: 15,
      },
      {
        dia: "2026-06-17",
        total: 134,
        icu4: 33,
        gestionables: 63,
        validos: 10,
      },
      {
        dia: "2026-06-18",
        total: 210,
        icu4: 77,
        gestionables: 122,
        validos: 27,
      },
      {
        dia: "2026-06-19",
        total: 203,
        icu4: 46,
        gestionables: 98,
        validos: 18,
      },
      {
        dia: "2026-06-20",
        total: 183,
        icu4: 72,
        gestionables: 103,
        validos: 20,
      },
      { dia: "2026-06-21", total: 78, icu4: 17, gestionables: 41, validos: 11 },
      { dia: "2026-06-22", total: 56, icu4: 7, gestionables: 23, validos: 5 },
      {
        dia: "2026-06-23",
        total: 128,
        icu4: 25,
        gestionables: 56,
        validos: 16,
      },
      {
        dia: "2026-06-24",
        total: 220,
        icu4: 71,
        gestionables: 120,
        validos: 26,
      },
      {
        dia: "2026-06-25",
        total: 135,
        icu4: 44,
        gestionables: 70,
        validos: 15,
      },
      { dia: "2026-06-26", total: 96, icu4: 18, gestionables: 39, validos: 6 },
      { dia: "2026-06-27", total: 127, icu4: 35, gestionables: 63, validos: 7 },
      { dia: "2026-06-28", total: 92, icu4: 38, gestionables: 53, validos: 11 },
      { dia: "2026-06-29", total: 70, icu4: 14, gestionables: 32, validos: 4 },
      { dia: "2026-06-30", total: 17, icu4: 2, gestionables: 5, validos: 1 },
    ],
    route: [
      { dim: "Ruta 1", total: 1510, icu4: 430 },
      { dim: "Ruta 2", total: 949, icu4: 513 },
      { dim: "Ruta 3", total: 310, icu4: 64 },
      { dim: "Ruta 4", total: 262, icu4: 57 },
      { dim: "Ruta 5", total: 173, icu4: 41 },
      { dim: "Ruta 6", total: 119, icu4: 16 },
      { dim: "Ruta 7", total: 118, icu4: 28 },
      { dim: "Ruta 8", total: 100, icu4: 31 },
      { dim: "Ruta 9", total: 90, icu4: 15 },
      { dim: "Ruta 10", total: 71, icu4: 3 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 985, icu4: 162 },
      { dim: "Transportista 8", total: 465, icu4: 363 },
      { dim: "Transportista 3", total: 250, icu4: 73 },
      { dim: "Transportista 9", total: 188, icu4: 82 },
      { dim: "Transportista 2", total: 167, icu4: 33 },
      { dim: "Transportista 10", total: 165, icu4: 54 },
      { dim: "Transportista 11", total: 165, icu4: 47 },
      { dim: "Transportista 12", total: 147, icu4: 42 },
      { dim: "Transportista 13", total: 141, icu4: 48 },
      { dim: "Transportista 14", total: 133, icu4: 36 },
    ],
    driver: [
      { dim: "Conductor 9", total: 105, icu4: 24 },
      { dim: "Conductor 13", total: 90, icu4: 23 },
      { dim: "Conductor 14", total: 66, icu4: 56 },
      { dim: "Conductor 3", total: 63, icu4: 8 },
      { dim: "Conductor 15", total: 62, icu4: 13 },
      { dim: "Conductor 16", total: 56, icu4: 6 },
      { dim: "Conductor 5", total: 56, icu4: 21 },
      { dim: "Conductor 17", total: 55, icu4: 11 },
      { dim: "Conductor 11", total: 55, icu4: 14 },
      { dim: "Conductor 12", total: 54, icu4: 7 },
    ],
  },
  "Continuous Resting Check": {
    kpis: {
      total: 1199,
      viajes: 569,
      conductores: 248,
      transportistas: 60,
      gestionables: 833,
      con_tratamiento: 505,
      validos: 252,
      invalidados: 253,
      icu1: 143,
      icu2: 223,
      icu3: 153,
      icu4: 680,
      blackcode: 680,
      sla_p50_min: 5.87,
      sla_p90_min: 7.21,
      trat_5min: 5,
      trat_2h: 482,
    },
    daily: [
      { dia: "2026-06-01", total: 27, icu4: 16, gestionables: 18, validos: 5 },
      { dia: "2026-06-02", total: 36, icu4: 25, gestionables: 28, validos: 12 },
      { dia: "2026-06-03", total: 45, icu4: 26, gestionables: 32, validos: 17 },
      { dia: "2026-06-04", total: 61, icu4: 40, gestionables: 44, validos: 11 },
      { dia: "2026-06-05", total: 53, icu4: 28, gestionables: 34, validos: 17 },
      { dia: "2026-06-06", total: 34, icu4: 17, gestionables: 23, validos: 7 },
      { dia: "2026-06-07", total: 39, icu4: 20, gestionables: 27, validos: 5 },
      { dia: "2026-06-08", total: 24, icu4: 14, gestionables: 15, validos: 4 },
      { dia: "2026-06-09", total: 45, icu4: 34, gestionables: 38, validos: 21 },
      { dia: "2026-06-10", total: 49, icu4: 24, gestionables: 32, validos: 13 },
      { dia: "2026-06-11", total: 37, icu4: 24, gestionables: 28, validos: 13 },
      { dia: "2026-06-12", total: 34, icu4: 16, gestionables: 23, validos: 5 },
      { dia: "2026-06-13", total: 48, icu4: 26, gestionables: 33, validos: 10 },
      { dia: "2026-06-14", total: 57, icu4: 31, gestionables: 41, validos: 14 },
      { dia: "2026-06-15", total: 25, icu4: 16, gestionables: 17, validos: 5 },
      { dia: "2026-06-16", total: 35, icu4: 21, gestionables: 24, validos: 4 },
      { dia: "2026-06-17", total: 72, icu4: 34, gestionables: 47, validos: 4 },
      { dia: "2026-06-18", total: 49, icu4: 28, gestionables: 33, validos: 12 },
      { dia: "2026-06-19", total: 54, icu4: 33, gestionables: 43, validos: 6 },
      { dia: "2026-06-20", total: 58, icu4: 28, gestionables: 37, validos: 8 },
      { dia: "2026-06-21", total: 47, icu4: 21, gestionables: 27, validos: 3 },
      { dia: "2026-06-22", total: 15, icu4: 9, gestionables: 11, validos: 3 },
      { dia: "2026-06-23", total: 33, icu4: 16, gestionables: 20, validos: 1 },
      { dia: "2026-06-24", total: 49, icu4: 30, gestionables: 36, validos: 21 },
      { dia: "2026-06-25", total: 46, icu4: 24, gestionables: 31, validos: 6 },
      { dia: "2026-06-26", total: 41, icu4: 27, gestionables: 31, validos: 10 },
      { dia: "2026-06-27", total: 31, icu4: 16, gestionables: 21, validos: 4 },
      { dia: "2026-06-28", total: 22, icu4: 17, gestionables: 18, validos: 5 },
      { dia: "2026-06-29", total: 26, icu4: 15, gestionables: 17, validos: 3 },
      { dia: "2026-06-30", total: 7, icu4: 4, gestionables: 4, validos: 3 },
    ],
    route: [
      { dim: "Ruta 1", total: 467, icu4: 250 },
      { dim: "Ruta 2", total: 166, icu4: 115 },
      { dim: "Ruta 3", total: 114, icu4: 68 },
      { dim: "Ruta 6", total: 89, icu4: 33 },
      { dim: "Ruta 7", total: 66, icu4: 25 },
      { dim: "Ruta 4", total: 56, icu4: 37 },
      { dim: "Ruta 5", total: 39, icu4: 24 },
      { dim: "Ruta 11", total: 27, icu4: 16 },
      { dim: "Ruta 8", total: 24, icu4: 18 },
      { dim: "Ruta 12", total: 17, icu4: 7 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 351, icu4: 149 },
      { dim: "Transportista 4", total: 80, icu4: 48 },
      { dim: "Transportista 2", total: 59, icu4: 40 },
      { dim: "Transportista 15", total: 55, icu4: 28 },
      { dim: "Transportista 3", total: 44, icu4: 24 },
      { dim: "Transportista 12", total: 39, icu4: 25 },
      { dim: "Transportista 11", total: 32, icu4: 17 },
      { dim: "Transportista 8", total: 32, icu4: 27 },
      { dim: "Transportista 13", total: 31, icu4: 18 },
      { dim: "Transportista 10", total: 31, icu4: 19 },
    ],
    driver: [
      { dim: "Conductor 12", total: 25, icu4: 5 },
      { dim: "Conductor 3", total: 24, icu4: 9 },
      { dim: "Conductor 2", total: 24, icu4: 9 },
      { dim: "Conductor 9", total: 24, icu4: 12 },
      { dim: "Conductor 18", total: 24, icu4: 7 },
      { dim: "Conductor 19", total: 21, icu4: 7 },
      { dim: "Conductor 4", total: 20, icu4: 9 },
      { dim: "Conductor 10", total: 17, icu4: 6 },
      { dim: "Conductor 20", total: 17, icu4: 6 },
      { dim: "Conductor 17", total: 17, icu4: 7 },
    ],
  },
  Deviation_Eta_Early: {
    kpis: {
      total: 1202,
      viajes: 629,
      conductores: 268,
      transportistas: 55,
      gestionables: 0,
      con_tratamiento: 645,
      validos: 645,
      invalidados: 0,
      icu1: 440,
      icu2: 205,
      icu3: 106,
      icu4: 451,
      blackcode: 451,
      sla_p50_min: 5.56,
      sla_p90_min: 5.9,
      trat_5min: 0,
      trat_2h: 645,
    },
    daily: [
      { dia: "2026-06-01", total: 30, icu4: 18, gestionables: 0, validos: 9 },
      { dia: "2026-06-02", total: 48, icu4: 24, gestionables: 0, validos: 18 },
      { dia: "2026-06-03", total: 46, icu4: 20, gestionables: 0, validos: 24 },
      { dia: "2026-06-04", total: 47, icu4: 7, gestionables: 0, validos: 37 },
      { dia: "2026-06-05", total: 34, icu4: 19, gestionables: 0, validos: 12 },
      { dia: "2026-06-06", total: 51, icu4: 13, gestionables: 0, validos: 30 },
      { dia: "2026-06-07", total: 38, icu4: 0, gestionables: 0, validos: 35 },
      { dia: "2026-06-08", total: 41, icu4: 19, gestionables: 0, validos: 19 },
      { dia: "2026-06-09", total: 57, icu4: 20, gestionables: 0, validos: 27 },
      { dia: "2026-06-10", total: 54, icu4: 15, gestionables: 0, validos: 34 },
      { dia: "2026-06-11", total: 32, icu4: 11, gestionables: 0, validos: 19 },
      { dia: "2026-06-12", total: 40, icu4: 26, gestionables: 0, validos: 9 },
      { dia: "2026-06-13", total: 40, icu4: 17, gestionables: 0, validos: 21 },
      { dia: "2026-06-14", total: 16, icu4: 4, gestionables: 0, validos: 10 },
      { dia: "2026-06-15", total: 47, icu4: 28, gestionables: 0, validos: 17 },
      { dia: "2026-06-16", total: 59, icu4: 29, gestionables: 0, validos: 22 },
      { dia: "2026-06-17", total: 75, icu4: 26, gestionables: 0, validos: 43 },
      { dia: "2026-06-18", total: 43, icu4: 15, gestionables: 0, validos: 23 },
      { dia: "2026-06-19", total: 43, icu4: 18, gestionables: 0, validos: 25 },
      { dia: "2026-06-20", total: 36, icu4: 7, gestionables: 0, validos: 25 },
      { dia: "2026-06-21", total: 15, icu4: 4, gestionables: 0, validos: 6 },
      { dia: "2026-06-22", total: 30, icu4: 13, gestionables: 0, validos: 16 },
      { dia: "2026-06-23", total: 51, icu4: 23, gestionables: 0, validos: 24 },
      { dia: "2026-06-24", total: 37, icu4: 15, gestionables: 0, validos: 20 },
      { dia: "2026-06-25", total: 29, icu4: 8, gestionables: 0, validos: 19 },
      { dia: "2026-06-26", total: 51, icu4: 17, gestionables: 0, validos: 29 },
      { dia: "2026-06-27", total: 50, icu4: 14, gestionables: 0, validos: 35 },
      { dia: "2026-06-28", total: 17, icu4: 2, gestionables: 0, validos: 15 },
      { dia: "2026-06-29", total: 16, icu4: 3, gestionables: 0, validos: 10 },
      { dia: "2026-06-30", total: 29, icu4: 16, gestionables: 0, validos: 12 },
    ],
    route: [
      { dim: "Ruta 1", total: 349, icu4: 233 },
      { dim: "Ruta 13", total: 249, icu4: 13 },
      { dim: "Ruta 3", total: 171, icu4: 80 },
      { dim: "Ruta 14", total: 145, icu4: 0 },
      { dim: "Ruta 2", total: 117, icu4: 82 },
      { dim: "Ruta 15", total: 67, icu4: 16 },
      { dim: "Ruta 16", total: 64, icu4: 7 },
      { dim: "Ruta 9", total: 13, icu4: 12 },
      { dim: "Ruta 17", total: 11, icu4: 3 },
      { dim: "Ruta 18", total: 10, icu4: 3 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 475, icu4: 70 },
      { dim: "Transportista 2", total: 74, icu4: 36 },
      { dim: "Transportista 5", total: 69, icu4: 5 },
      { dim: "Transportista 11", total: 56, icu4: 24 },
      { dim: "Transportista 16", total: 54, icu4: 14 },
      { dim: "Transportista 4", total: 52, icu4: 34 },
      { dim: "Transportista 9", total: 39, icu4: 23 },
      { dim: "Transportista 10", total: 37, icu4: 27 },
      { dim: "Transportista 3", total: 34, icu4: 25 },
      { dim: "Transportista 17", total: 22, icu4: 13 },
    ],
    driver: [
      { dim: "Conductor 6", total: 39, icu4: 0 },
      { dim: "Conductor 10", total: 26, icu4: 5 },
      { dim: "Conductor 21", total: 25, icu4: 0 },
      { dim: "Conductor 4", total: 22, icu4: 1 },
      { dim: "Conductor 22", total: 22, icu4: 1 },
      { dim: "Conductor 23", total: 20, icu4: 1 },
      { dim: "Conductor 24", total: 20, icu4: 0 },
      { dim: "Conductor 25", total: 18, icu4: 0 },
      { dim: "Conductor 26", total: 17, icu4: 1 },
      { dim: "Conductor 27", total: 17, icu4: 1 },
    ],
  },
  Deviation_Eta_Late: {
    kpis: {
      total: 930,
      viajes: 447,
      conductores: 209,
      transportistas: 50,
      gestionables: 0,
      con_tratamiento: 610,
      validos: 610,
      invalidados: 0,
      icu1: 490,
      icu2: 120,
      icu3: 99,
      icu4: 221,
      blackcode: 221,
      sla_p50_min: 5.53,
      sla_p90_min: 5.9,
      trat_5min: 0,
      trat_2h: 610,
    },
    daily: [
      { dia: "2026-06-01", total: 37, icu4: 4, gestionables: 0, validos: 31 },
      { dia: "2026-06-02", total: 16, icu4: 8, gestionables: 0, validos: 6 },
      { dia: "2026-06-03", total: 53, icu4: 8, gestionables: 0, validos: 38 },
      { dia: "2026-06-04", total: 46, icu4: 15, gestionables: 0, validos: 30 },
      { dia: "2026-06-05", total: 46, icu4: 11, gestionables: 0, validos: 33 },
      { dia: "2026-06-06", total: 30, icu4: 7, gestionables: 0, validos: 19 },
      { dia: "2026-06-07", total: 17, icu4: 8, gestionables: 0, validos: 8 },
      { dia: "2026-06-08", total: 26, icu4: 3, gestionables: 0, validos: 12 },
      { dia: "2026-06-09", total: 20, icu4: 10, gestionables: 0, validos: 8 },
      { dia: "2026-06-10", total: 28, icu4: 6, gestionables: 0, validos: 20 },
      { dia: "2026-06-11", total: 20, icu4: 4, gestionables: 0, validos: 12 },
      { dia: "2026-06-12", total: 34, icu4: 9, gestionables: 0, validos: 23 },
      { dia: "2026-06-13", total: 41, icu4: 5, gestionables: 0, validos: 32 },
      { dia: "2026-06-14", total: 41, icu4: 8, gestionables: 0, validos: 27 },
      { dia: "2026-06-15", total: 15, icu4: 4, gestionables: 0, validos: 9 },
      { dia: "2026-06-16", total: 20, icu4: 6, gestionables: 0, validos: 13 },
      { dia: "2026-06-17", total: 33, icu4: 5, gestionables: 0, validos: 23 },
      { dia: "2026-06-18", total: 43, icu4: 9, gestionables: 0, validos: 31 },
      { dia: "2026-06-19", total: 28, icu4: 12, gestionables: 0, validos: 13 },
      { dia: "2026-06-20", total: 25, icu4: 6, gestionables: 0, validos: 16 },
      { dia: "2026-06-21", total: 13, icu4: 3, gestionables: 0, validos: 8 },
      { dia: "2026-06-22", total: 30, icu4: 1, gestionables: 0, validos: 28 },
      { dia: "2026-06-23", total: 16, icu4: 5, gestionables: 0, validos: 8 },
      { dia: "2026-06-24", total: 62, icu4: 14, gestionables: 0, validos: 42 },
      { dia: "2026-06-25", total: 46, icu4: 12, gestionables: 0, validos: 31 },
      { dia: "2026-06-26", total: 21, icu4: 9, gestionables: 0, validos: 9 },
      { dia: "2026-06-27", total: 22, icu4: 8, gestionables: 0, validos: 11 },
      { dia: "2026-06-28", total: 12, icu4: 5, gestionables: 0, validos: 4 },
      { dia: "2026-06-29", total: 24, icu4: 6, gestionables: 0, validos: 15 },
      { dia: "2026-06-30", total: 65, icu4: 10, gestionables: 0, validos: 50 },
    ],
    route: [
      { dim: "Ruta 1", total: 274, icu4: 57 },
      { dim: "Ruta 2", total: 152, icu4: 13 },
      { dim: "Ruta 15", total: 141, icu4: 117 },
      { dim: "Ruta 13", total: 120, icu4: 11 },
      { dim: "Ruta 3", total: 105, icu4: 7 },
      { dim: "Ruta 16", total: 63, icu4: 3 },
      { dim: "Ruta 7", total: 54, icu4: 12 },
      { dim: "Ruta 14", total: 9, icu4: 0 },
      { dim: "Ruta 9", total: 6, icu4: 0 },
      { dim: "Ruta 17", total: 4, icu4: 0 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 178, icu4: 46 },
      { dim: "Transportista 16", total: 80, icu4: 65 },
      { dim: "Transportista 5", total: 71, icu4: 21 },
      { dim: "Transportista 4", total: 69, icu4: 2 },
      { dim: "Transportista 18", total: 52, icu4: 1 },
      { dim: "Transportista 3", total: 49, icu4: 6 },
      { dim: "Transportista 17", total: 43, icu4: 6 },
      { dim: "Transportista 2", total: 41, icu4: 3 },
      { dim: "Transportista 6", total: 32, icu4: 0 },
      { dim: "Transportista 10", total: 28, icu4: 10 },
    ],
    driver: [
      { dim: "Conductor 28", total: 28, icu4: 0 },
      { dim: "Conductor 29", total: 25, icu4: 0 },
      { dim: "Conductor 30", total: 20, icu4: 15 },
      { dim: "Conductor 31", total: 19, icu4: 16 },
      { dim: "Conductor 32", total: 19, icu4: 1 },
      { dim: "Conductor 33", total: 19, icu4: 17 },
      { dim: "Conductor 34", total: 17, icu4: 1 },
      { dim: "Conductor 26", total: 15, icu4: 1 },
      { dim: "Conductor 35", total: 14, icu4: 11 },
      { dim: "Conductor 36", total: 14, icu4: 1 },
    ],
  },
  "Double Driver Rotation Check": {
    kpis: {
      total: 398,
      viajes: 98,
      conductores: 50,
      transportistas: 24,
      gestionables: 0,
      con_tratamiento: 391,
      validos: 334,
      invalidados: 57,
      icu1: 0,
      icu2: 0,
      icu3: 398,
      icu4: 0,
      blackcode: 0,
      sla_p50_min: 5.98,
      sla_p90_min: 10.75,
      trat_5min: 19,
      trat_2h: 390,
    },
    daily: [
      { dia: "2026-06-01", total: 5, icu4: 0, gestionables: 0, validos: 4 },
      { dia: "2026-06-02", total: 15, icu4: 0, gestionables: 0, validos: 15 },
      { dia: "2026-06-03", total: 17, icu4: 0, gestionables: 0, validos: 14 },
      { dia: "2026-06-04", total: 18, icu4: 0, gestionables: 0, validos: 15 },
      { dia: "2026-06-05", total: 17, icu4: 0, gestionables: 0, validos: 17 },
      { dia: "2026-06-06", total: 11, icu4: 0, gestionables: 0, validos: 10 },
      { dia: "2026-06-07", total: 2, icu4: 0, gestionables: 0, validos: 1 },
      { dia: "2026-06-08", total: 2, icu4: 0, gestionables: 0, validos: 2 },
      { dia: "2026-06-09", total: 7, icu4: 0, gestionables: 0, validos: 7 },
      { dia: "2026-06-10", total: 11, icu4: 0, gestionables: 0, validos: 10 },
      { dia: "2026-06-11", total: 16, icu4: 0, gestionables: 0, validos: 8 },
      { dia: "2026-06-12", total: 10, icu4: 0, gestionables: 0, validos: 9 },
      { dia: "2026-06-13", total: 10, icu4: 0, gestionables: 0, validos: 9 },
      { dia: "2026-06-14", total: 8, icu4: 0, gestionables: 0, validos: 6 },
      { dia: "2026-06-15", total: 9, icu4: 0, gestionables: 0, validos: 9 },
      { dia: "2026-06-16", total: 8, icu4: 0, gestionables: 0, validos: 8 },
      { dia: "2026-06-17", total: 9, icu4: 0, gestionables: 0, validos: 9 },
      { dia: "2026-06-18", total: 7, icu4: 0, gestionables: 0, validos: 6 },
      { dia: "2026-06-19", total: 24, icu4: 0, gestionables: 0, validos: 22 },
      { dia: "2026-06-20", total: 22, icu4: 0, gestionables: 0, validos: 15 },
      { dia: "2026-06-21", total: 11, icu4: 0, gestionables: 0, validos: 6 },
      { dia: "2026-06-22", total: 6, icu4: 0, gestionables: 0, validos: 1 },
      { dia: "2026-06-23", total: 14, icu4: 0, gestionables: 0, validos: 12 },
      { dia: "2026-06-24", total: 20, icu4: 0, gestionables: 0, validos: 19 },
      { dia: "2026-06-25", total: 18, icu4: 0, gestionables: 0, validos: 16 },
      { dia: "2026-06-26", total: 39, icu4: 0, gestionables: 0, validos: 37 },
      { dia: "2026-06-27", total: 35, icu4: 0, gestionables: 0, validos: 30 },
      { dia: "2026-06-28", total: 16, icu4: 0, gestionables: 0, validos: 9 },
      { dia: "2026-06-29", total: 5, icu4: 0, gestionables: 0, validos: 2 },
      { dia: "2026-06-30", total: 6, icu4: 0, gestionables: 0, validos: 6 },
    ],
    route: [
      { dim: "Ruta 1", total: 193, icu4: 0 },
      { dim: "Ruta 2", total: 66, icu4: 0 },
      { dim: "Ruta 8", total: 22, icu4: 0 },
      { dim: "Ruta 4", total: 21, icu4: 0 },
      { dim: "Ruta 5", total: 19, icu4: 0 },
      { dim: "Ruta 3", total: 19, icu4: 0 },
      { dim: "Ruta 19", total: 17, icu4: 0 },
      { dim: "Ruta 7", total: 11, icu4: 0 },
      { dim: "Ruta 20", total: 10, icu4: 0 },
      { dim: "Ruta 21", total: 4, icu4: 0 },
    ],
    carrier: [
      { dim: "Transportista 19", total: 65, icu4: 0 },
      { dim: "Transportista 3", total: 46, icu4: 0 },
      { dim: "Transportista 20", total: 43, icu4: 0 },
      { dim: "Conductor 38", total: 39, icu4: 0 },
      { dim: "Transportista 14", total: 36, icu4: 0 },
      { dim: "Transportista 22", total: 25, icu4: 0 },
      { dim: "Transportista 23", total: 22, icu4: 0 },
      { dim: "Transportista 24", total: 15, icu4: 0 },
      { dim: "Transportista 25", total: 14, icu4: 0 },
      { dim: "Transportista 12", total: 13, icu4: 0 },
    ],
    driver: [
      { dim: "Conductor 37", total: 29, icu4: 0 },
      { dim: "Conductor 38", total: 27, icu4: 0 },
      { dim: "Conductor 39", total: 18, icu4: 0 },
      { dim: "Conductor 40", total: 17, icu4: 0 },
      { dim: "Conductor 41", total: 17, icu4: 0 },
      { dim: "Conductor 42", total: 17, icu4: 0 },
      { dim: "Conductor 43", total: 15, icu4: 0 },
      { dim: "Conductor 44", total: 15, icu4: 0 },
      { dim: "Conductor 45", total: 15, icu4: 0 },
      { dim: "Conductor 46", total: 15, icu4: 0 },
    ],
  },
  "Fatigue And Drowsiness Sensor": {
    kpis: {
      total: 179,
      viajes: 179,
      conductores: 31,
      transportistas: 2,
      gestionables: 0,
      con_tratamiento: 0,
      validos: 0,
      invalidados: 0,
      icu1: 179,
      icu2: 0,
      icu3: 0,
      icu4: 0,
      blackcode: 0,
      sla_p50_min: null,
      sla_p90_min: null,
      trat_5min: 0,
      trat_2h: 0,
    },
    daily: [
      { dia: "2026-06-01", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-02", total: 10, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-03", total: 6, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-04", total: 8, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-05", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-06", total: 8, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-07", total: 6, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-08", total: 8, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-09", total: 9, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-10", total: 7, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-11", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-12", total: 4, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-13", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-14", total: 3, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-15", total: 10, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-16", total: 8, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-17", total: 6, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-18", total: 9, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-19", total: 10, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-20", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-22", total: 3, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-23", total: 8, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-24", total: 6, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-25", total: 7, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-26", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-27", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-28", total: 2, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-29", total: 2, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-30", total: 4, icu4: 0, gestionables: 0, validos: 0 },
    ],
    route: [
      { dim: "Ruta 13", total: 58, icu4: 0 },
      { dim: "Ruta 15", total: 22, icu4: 0 },
      { dim: "Ruta 1", total: 22, icu4: 0 },
      { dim: "Ruta 4", total: 16, icu4: 0 },
      { dim: "Ruta 6", total: 14, icu4: 0 },
      { dim: "Ruta 16", total: 14, icu4: 0 },
      { dim: "Ruta 7", total: 7, icu4: 0 },
      { dim: "Ruta 14", total: 4, icu4: 0 },
      { dim: "Ruta 22", total: 4, icu4: 0 },
      { dim: "Ruta 3", total: 3, icu4: 0 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 167, icu4: 0 },
      { dim: "Transportista 26", total: 12, icu4: 0 },
    ],
    driver: [
      { dim: "Conductor 33", total: 14, icu4: 0 },
      { dim: "Conductor 24", total: 13, icu4: 0 },
      { dim: "Conductor 47", total: 10, icu4: 0 },
      { dim: "Conductor 48", total: 9, icu4: 0 },
      { dim: "Conductor 31", total: 9, icu4: 0 },
      { dim: "Conductor 2", total: 8, icu4: 0 },
      { dim: "Conductor 1", total: 7, icu4: 0 },
      { dim: "Conductor 49", total: 7, icu4: 0 },
      { dim: "Conductor 50", total: 7, icu4: 0 },
      { dim: "Conductor 16", total: 7, icu4: 0 },
    ],
  },
  "Lost Signal": {
    kpis: {
      total: 17624,
      viajes: 2067,
      conductores: 383,
      transportistas: 80,
      gestionables: 0,
      con_tratamiento: 1513,
      validos: 447,
      invalidados: 1066,
      icu1: 14234,
      icu2: 1437,
      icu3: 996,
      icu4: 957,
      blackcode: 957,
      sla_p50_min: 120.28,
      sla_p90_min: 120.88,
      trat_5min: 25,
      trat_2h: 574,
    },
    daily: [
      { dia: "2026-06-01", total: 425, icu4: 20, gestionables: 0, validos: 10 },
      { dia: "2026-06-02", total: 625, icu4: 14, gestionables: 0, validos: 16 },
      { dia: "2026-06-03", total: 782, icu4: 38, gestionables: 0, validos: 20 },
      { dia: "2026-06-04", total: 809, icu4: 27, gestionables: 0, validos: 16 },
      { dia: "2026-06-05", total: 582, icu4: 19, gestionables: 0, validos: 14 },
      { dia: "2026-06-06", total: 577, icu4: 17, gestionables: 0, validos: 5 },
      { dia: "2026-06-07", total: 584, icu4: 53, gestionables: 0, validos: 18 },
      { dia: "2026-06-08", total: 490, icu4: 45, gestionables: 0, validos: 21 },
      { dia: "2026-06-09", total: 535, icu4: 22, gestionables: 0, validos: 14 },
      { dia: "2026-06-10", total: 815, icu4: 27, gestionables: 0, validos: 25 },
      { dia: "2026-06-11", total: 552, icu4: 39, gestionables: 0, validos: 13 },
      { dia: "2026-06-12", total: 548, icu4: 39, gestionables: 0, validos: 22 },
      { dia: "2026-06-13", total: 639, icu4: 41, gestionables: 0, validos: 19 },
      { dia: "2026-06-14", total: 494, icu4: 38, gestionables: 0, validos: 22 },
      { dia: "2026-06-15", total: 501, icu4: 20, gestionables: 0, validos: 11 },
      { dia: "2026-06-16", total: 686, icu4: 35, gestionables: 0, validos: 18 },
      { dia: "2026-06-17", total: 807, icu4: 55, gestionables: 0, validos: 22 },
      { dia: "2026-06-18", total: 699, icu4: 26, gestionables: 0, validos: 12 },
      { dia: "2026-06-19", total: 713, icu4: 35, gestionables: 0, validos: 19 },
      { dia: "2026-06-20", total: 670, icu4: 50, gestionables: 0, validos: 12 },
      { dia: "2026-06-21", total: 439, icu4: 44, gestionables: 0, validos: 14 },
      { dia: "2026-06-22", total: 316, icu4: 10, gestionables: 0, validos: 5 },
      { dia: "2026-06-23", total: 386, icu4: 13, gestionables: 0, validos: 7 },
      { dia: "2026-06-24", total: 667, icu4: 24, gestionables: 0, validos: 14 },
      { dia: "2026-06-25", total: 772, icu4: 48, gestionables: 0, validos: 24 },
      { dia: "2026-06-26", total: 739, icu4: 40, gestionables: 0, validos: 13 },
      { dia: "2026-06-27", total: 637, icu4: 46, gestionables: 0, validos: 18 },
      { dia: "2026-06-28", total: 422, icu4: 34, gestionables: 0, validos: 13 },
      { dia: "2026-06-29", total: 397, icu4: 24, gestionables: 0, validos: 1 },
      { dia: "2026-06-30", total: 316, icu4: 14, gestionables: 0, validos: 9 },
    ],
    route: [
      { dim: "Ruta 1", total: 5333, icu4: 275 },
      { dim: "Ruta 2", total: 2416, icu4: 238 },
      { dim: "Ruta 13", total: 1475, icu4: 35 },
      { dim: "Ruta 3", total: 917, icu4: 66 },
      { dim: "Ruta 23", total: 565, icu4: 28 },
      { dim: "Ruta 7", total: 562, icu4: 36 },
      { dim: "Ruta 4", total: 546, icu4: 30 },
      { dim: "Ruta 16", total: 492, icu4: 5 },
      { dim: "Ruta 8", total: 411, icu4: 22 },
      { dim: "Ruta 15", total: 339, icu4: 18 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 3536, icu4: 39 },
      { dim: "Transportista 6", total: 854, icu4: 69 },
      { dim: "Transportista 2", total: 821, icu4: 11 },
      { dim: "Transportista 12", total: 800, icu4: 6 },
      { dim: "Transportista 7", total: 789, icu4: 64 },
      { dim: "Transportista 5", total: 757, icu4: 32 },
      { dim: "Transportista 8", total: 697, icu4: 140 },
      { dim: "Transportista 4", total: 655, icu4: 14 },
      { dim: "Transportista 9", total: 599, icu4: 22 },
      { dim: "Transportista 10", total: 524, icu4: 48 },
    ],
    driver: [
      { dim: "Conductor 11", total: 334, icu4: 29 },
      { dim: "Conductor 28", total: 289, icu4: 21 },
      { dim: "Conductor 51", total: 244, icu4: 1 },
      { dim: "Conductor 52", total: 218, icu4: 18 },
      { dim: "Conductor 53", total: 207, icu4: 15 },
      { dim: "Conductor 54", total: 192, icu4: 4 },
      { dim: "Conductor 55", total: 182, icu4: 2 },
      { dim: "Conductor 56", total: 177, icu4: 11 },
      { dim: "Conductor 57", total: 174, icu4: 4 },
      { dim: "Conductor 58", total: 160, icu4: 1 },
    ],
  },
  "No Authorized Zone Stop": {
    kpis: {
      total: 3097,
      viajes: 1215,
      conductores: 360,
      transportistas: 78,
      gestionables: 0,
      con_tratamiento: 1139,
      validos: 574,
      invalidados: 565,
      icu1: 1215,
      icu2: 485,
      icu3: 479,
      icu4: 918,
      blackcode: 918,
      sla_p50_min: 5.89,
      sla_p90_min: 14.5,
      trat_5min: 49,
      trat_2h: 1061,
    },
    daily: [
      { dia: "2026-06-01", total: 128, icu4: 43, gestionables: 0, validos: 31 },
      { dia: "2026-06-02", total: 114, icu4: 37, gestionables: 0, validos: 41 },
      { dia: "2026-06-03", total: 138, icu4: 38, gestionables: 0, validos: 31 },
      { dia: "2026-06-04", total: 149, icu4: 38, gestionables: 0, validos: 21 },
      { dia: "2026-06-05", total: 112, icu4: 32, gestionables: 0, validos: 20 },
      { dia: "2026-06-06", total: 79, icu4: 22, gestionables: 0, validos: 23 },
      { dia: "2026-06-07", total: 51, icu4: 17, gestionables: 0, validos: 9 },
      { dia: "2026-06-08", total: 181, icu4: 49, gestionables: 0, validos: 50 },
      { dia: "2026-06-09", total: 116, icu4: 36, gestionables: 0, validos: 31 },
      { dia: "2026-06-10", total: 114, icu4: 31, gestionables: 0, validos: 22 },
      { dia: "2026-06-11", total: 126, icu4: 47, gestionables: 0, validos: 16 },
      { dia: "2026-06-12", total: 129, icu4: 34, gestionables: 0, validos: 20 },
      { dia: "2026-06-13", total: 97, icu4: 23, gestionables: 0, validos: 11 },
      { dia: "2026-06-14", total: 39, icu4: 12, gestionables: 0, validos: 10 },
      { dia: "2026-06-15", total: 139, icu4: 40, gestionables: 0, validos: 21 },
      { dia: "2026-06-16", total: 108, icu4: 28, gestionables: 0, validos: 20 },
      { dia: "2026-06-17", total: 132, icu4: 41, gestionables: 0, validos: 20 },
      { dia: "2026-06-18", total: 136, icu4: 35, gestionables: 0, validos: 18 },
      { dia: "2026-06-19", total: 111, icu4: 41, gestionables: 0, validos: 25 },
      { dia: "2026-06-20", total: 58, icu4: 17, gestionables: 0, validos: 11 },
      { dia: "2026-06-21", total: 13, icu4: 3, gestionables: 0, validos: 1 },
      { dia: "2026-06-22", total: 114, icu4: 34, gestionables: 0, validos: 18 },
      { dia: "2026-06-23", total: 130, icu4: 41, gestionables: 0, validos: 19 },
      { dia: "2026-06-24", total: 118, icu4: 39, gestionables: 0, validos: 21 },
      { dia: "2026-06-25", total: 87, icu4: 28, gestionables: 0, validos: 11 },
      { dia: "2026-06-26", total: 127, icu4: 37, gestionables: 0, validos: 17 },
      { dia: "2026-06-27", total: 74, icu4: 23, gestionables: 0, validos: 7 },
      { dia: "2026-06-28", total: 16, icu4: 4, gestionables: 0, validos: 2 },
      { dia: "2026-06-29", total: 15, icu4: 5, gestionables: 0, validos: 2 },
      { dia: "2026-06-30", total: 146, icu4: 43, gestionables: 0, validos: 25 },
    ],
    route: [
      { dim: "Ruta 1", total: 664, icu4: 224 },
      { dim: "Ruta 3", total: 323, icu4: 94 },
      { dim: "Ruta 13", total: 284, icu4: 57 },
      { dim: "Ruta 2", total: 187, icu4: 68 },
      { dim: "Ruta 15", total: 144, icu4: 45 },
      { dim: "Ruta 4", total: 132, icu4: 41 },
      { dim: "Ruta 14", total: 125, icu4: 27 },
      { dim: "Ruta 5", total: 86, icu4: 23 },
      { dim: "Ruta 7", total: 71, icu4: 19 },
      { dim: "Ruta 6", total: 70, icu4: 20 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 949, icu4: 208 },
      { dim: "Transportista 4", total: 213, icu4: 64 },
      { dim: "Transportista 16", total: 181, icu4: 55 },
      { dim: "Transportista 5", total: 164, icu4: 47 },
      { dim: "Transportista 2", total: 125, icu4: 44 },
      { dim: "Transportista 3", total: 116, icu4: 37 },
      { dim: "Transportista 14", total: 98, icu4: 34 },
      { dim: "Transportista 27", total: 76, icu4: 19 },
      { dim: "Transportista 11", total: 69, icu4: 23 },
      { dim: "Transportista 15", total: 60, icu4: 16 },
    ],
    driver: [
      { dim: "Conductor 59", total: 43, icu4: 7 },
      { dim: "Conductor 25", total: 42, icu4: 9 },
      { dim: "Conductor 9", total: 35, icu4: 7 },
      { dim: "Conductor 10", total: 34, icu4: 11 },
      { dim: "Conductor 3", total: 34, icu4: 6 },
      { dim: "Conductor 30", total: 31, icu4: 9 },
      { dim: "Conductor 60", total: 31, icu4: 13 },
      { dim: "Conductor 4", total: 31, icu4: 5 },
      { dim: "Conductor 35", total: 30, icu4: 10 },
      { dim: "Conductor 24", total: 29, icu4: 5 },
    ],
  },
  "Off Hours Driving": {
    kpis: {
      total: 802,
      viajes: 163,
      conductores: 112,
      transportistas: 37,
      gestionables: 224,
      con_tratamiento: 80,
      validos: 42,
      invalidados: 38,
      icu1: 266,
      icu2: 312,
      icu3: 198,
      icu4: 26,
      blackcode: 26,
      sla_p50_min: 9.73,
      sla_p90_min: 120.59,
      trat_5min: 3,
      trat_2h: 55,
    },
    daily: [
      { dia: "2026-06-01", total: 4, icu4: 1, gestionables: 2, validos: 0 },
      { dia: "2026-06-02", total: 66, icu4: 2, gestionables: 13, validos: 2 },
      { dia: "2026-06-03", total: 23, icu4: 0, gestionables: 5, validos: 4 },
      { dia: "2026-06-04", total: 46, icu4: 4, gestionables: 13, validos: 2 },
      { dia: "2026-06-05", total: 32, icu4: 0, gestionables: 7, validos: 0 },
      { dia: "2026-06-06", total: 23, icu4: 0, gestionables: 1, validos: 0 },
      { dia: "2026-06-07", total: 38, icu4: 0, gestionables: 6, validos: 4 },
      { dia: "2026-06-08", total: 10, icu4: 0, gestionables: 4, validos: 0 },
      { dia: "2026-06-09", total: 17, icu4: 0, gestionables: 4, validos: 1 },
      { dia: "2026-06-10", total: 16, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-11", total: 16, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-12", total: 40, icu4: 6, gestionables: 7, validos: 3 },
      { dia: "2026-06-13", total: 23, icu4: 0, gestionables: 10, validos: 1 },
      { dia: "2026-06-14", total: 16, icu4: 1, gestionables: 9, validos: 1 },
      { dia: "2026-06-15", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-16", total: 21, icu4: 0, gestionables: 6, validos: 0 },
      { dia: "2026-06-17", total: 4, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-18", total: 34, icu4: 1, gestionables: 7, validos: 2 },
      { dia: "2026-06-19", total: 101, icu4: 1, gestionables: 55, validos: 3 },
      { dia: "2026-06-20", total: 49, icu4: 3, gestionables: 16, validos: 5 },
      { dia: "2026-06-21", total: 23, icu4: 2, gestionables: 6, validos: 1 },
      { dia: "2026-06-22", total: 5, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-23", total: 21, icu4: 1, gestionables: 6, validos: 3 },
      { dia: "2026-06-24", total: 49, icu4: 0, gestionables: 9, validos: 0 },
      { dia: "2026-06-25", total: 21, icu4: 2, gestionables: 5, validos: 2 },
      { dia: "2026-06-26", total: 52, icu4: 1, gestionables: 24, validos: 5 },
      { dia: "2026-06-27", total: 21, icu4: 0, gestionables: 2, validos: 1 },
      { dia: "2026-06-28", total: 7, icu4: 0, gestionables: 3, validos: 1 },
      { dia: "2026-06-29", total: 4, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-30", total: 15, icu4: 1, gestionables: 4, validos: 1 },
    ],
    route: [
      { dim: "Ruta 1", total: 188, icu4: 6 },
      { dim: "Ruta 3", total: 142, icu4: 0 },
      { dim: "Ruta 5", total: 67, icu4: 8 },
      { dim: "Ruta 6", total: 55, icu4: 0 },
      { dim: "Ruta 13", total: 53, icu4: 0 },
      { dim: "Ruta 15", total: 53, icu4: 0 },
      { dim: "Ruta 4", total: 37, icu4: 1 },
      { dim: "Ruta 23", total: 25, icu4: 0 },
      { dim: "Ruta 24", total: 24, icu4: 0 },
      { dim: "Ruta 25", total: 18, icu4: 1 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 336, icu4: 0 },
      { dim: "Transportista 4", total: 51, icu4: 1 },
      { dim: "Transportista 5", total: 49, icu4: 0 },
      { dim: "Transportista 27", total: 28, icu4: 0 },
      { dim: "Transportista 11", total: 28, icu4: 0 },
      { dim: "Transportista 2", total: 26, icu4: 0 },
      { dim: "Transportista 17", total: 24, icu4: 0 },
      { dim: "Transportista 28", total: 24, icu4: 3 },
      { dim: "Transportista 3", total: 22, icu4: 0 },
      { dim: "Transportista 29", total: 19, icu4: 2 },
    ],
    driver: [
      { dim: "Conductor 10", total: 60, icu4: 0 },
      { dim: "Conductor 1", total: 41, icu4: 0 },
      { dim: "Conductor 9", total: 36, icu4: 0 },
      { dim: "Conductor 7", total: 34, icu4: 0 },
      { dim: "Conductor 61", total: 27, icu4: 0 },
      { dim: "Conductor 3", total: 27, icu4: 0 },
      { dim: "Conductor 62", total: 24, icu4: 0 },
      { dim: "Conductor 15", total: 24, icu4: 3 },
      { dim: "Conductor 4", total: 24, icu4: 0 },
      { dim: "Conductor 23", total: 22, icu4: 0 },
    ],
  },
  "Risk Zone Stop": {
    kpis: {
      total: 736,
      viajes: 307,
      conductores: 134,
      transportistas: 43,
      gestionables: 70,
      con_tratamiento: 51,
      validos: 23,
      invalidados: 28,
      icu1: 584,
      icu2: 82,
      icu3: 27,
      icu4: 43,
      blackcode: 43,
      sla_p50_min: 120.12,
      sla_p90_min: 120.94,
      trat_5min: 0,
      trat_2h: 25,
    },
    daily: [
      { dia: "2026-06-01", total: 14, icu4: 0, gestionables: 1, validos: 0 },
      { dia: "2026-06-02", total: 23, icu4: 0, gestionables: 2, validos: 1 },
      { dia: "2026-06-03", total: 55, icu4: 6, gestionables: 8, validos: 2 },
      { dia: "2026-06-04", total: 41, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-05", total: 13, icu4: 0, gestionables: 1, validos: 0 },
      { dia: "2026-06-06", total: 12, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-07", total: 19, icu4: 1, gestionables: 1, validos: 1 },
      { dia: "2026-06-08", total: 30, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-09", total: 15, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-10", total: 18, icu4: 2, gestionables: 2, validos: 0 },
      { dia: "2026-06-11", total: 36, icu4: 2, gestionables: 4, validos: 1 },
      { dia: "2026-06-12", total: 60, icu4: 13, gestionables: 18, validos: 8 },
      { dia: "2026-06-13", total: 10, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-14", total: 16, icu4: 1, gestionables: 1, validos: 1 },
      { dia: "2026-06-15", total: 23, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-16", total: 40, icu4: 2, gestionables: 6, validos: 3 },
      { dia: "2026-06-17", total: 28, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-18", total: 34, icu4: 0, gestionables: 1, validos: 0 },
      { dia: "2026-06-19", total: 20, icu4: 2, gestionables: 2, validos: 0 },
      { dia: "2026-06-20", total: 18, icu4: 2, gestionables: 5, validos: 1 },
      { dia: "2026-06-21", total: 11, icu4: 1, gestionables: 2, validos: 0 },
      { dia: "2026-06-22", total: 16, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-23", total: 20, icu4: 1, gestionables: 2, validos: 0 },
      { dia: "2026-06-24", total: 35, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-25", total: 6, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-26", total: 49, icu4: 3, gestionables: 3, validos: 1 },
      { dia: "2026-06-27", total: 26, icu4: 5, gestionables: 7, validos: 3 },
      { dia: "2026-06-28", total: 17, icu4: 0, gestionables: 0, validos: 0 },
      { dia: "2026-06-29", total: 13, icu4: 2, gestionables: 3, validos: 1 },
      { dia: "2026-06-30", total: 18, icu4: 0, gestionables: 1, validos: 0 },
    ],
    route: [
      { dim: "Ruta 1", total: 144, icu4: 16 },
      { dim: "Ruta 23", total: 99, icu4: 0 },
      { dim: "Ruta 26", total: 76, icu4: 0 },
      { dim: "Ruta 3", total: 62, icu4: 3 },
      { dim: "Ruta 6", total: 42, icu4: 0 },
      { dim: "Ruta 27", total: 36, icu4: 13 },
      { dim: "Ruta 28", total: 33, icu4: 0 },
      { dim: "Ruta 4", total: 31, icu4: 2 },
      { dim: "Ruta 7", total: 29, icu4: 5 },
      { dim: "Ruta 2", total: 25, icu4: 0 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 423, icu4: 4 },
      { dim: "Transportista 4", total: 36, icu4: 10 },
      { dim: "Transportista 30", total: 29, icu4: 0 },
      { dim: "Transportista 11", total: 24, icu4: 0 },
      { dim: "Transportista 14", total: 15, icu4: 1 },
      { dim: "Transportista 6", total: 13, icu4: 1 },
      { dim: "Transportista 18", total: 13, icu4: 0 },
      { dim: "Transportista 31", total: 12, icu4: 7 },
      { dim: "Transportista 15", total: 12, icu4: 4 },
      { dim: "Transportista 32", total: 12, icu4: 2 },
    ],
    driver: [
      { dim: "Conductor 63", total: 31, icu4: 0 },
      { dim: "Conductor 64", total: 29, icu4: 0 },
      { dim: "Conductor 65", total: 28, icu4: 0 },
      { dim: "Conductor 8", total: 26, icu4: 0 },
      { dim: "Conductor 3", total: 25, icu4: 0 },
      { dim: "Conductor 12", total: 23, icu4: 0 },
      { dim: "Conductor 61", total: 20, icu4: 0 },
      { dim: "Conductor 66", total: 20, icu4: 0 },
      { dim: "Conductor 67", total: 17, icu4: 0 },
      { dim: "Conductor 68", total: 17, icu4: 7 },
    ],
  },
  "Sos Button": {
    kpis: {
      total: 1,
      viajes: 1,
      conductores: 1,
      transportistas: 1,
      gestionables: 0,
      con_tratamiento: 1,
      validos: 0,
      invalidados: 1,
      icu1: 0,
      icu2: 0,
      icu3: 0,
      icu4: 1,
      blackcode: 1,
      sla_p50_min: 9.93,
      sla_p90_min: 9.93,
      trat_5min: 0,
      trat_2h: 1,
    },
    daily: [
      { dia: "2026-06-19", total: 1, icu4: 1, gestionables: 0, validos: 0 },
    ],
    route: [{ dim: "Ruta 26", total: 1, icu4: 1 }],
    carrier: [{ dim: "Transportista 14", total: 1, icu4: 1 }],
    driver: [{ dim: "Conductor 69", total: 1, icu4: 1 }],
  },
  "Speed Limit Standard": {
    kpis: {
      total: 25475,
      viajes: 1910,
      conductores: 371,
      transportistas: 76,
      gestionables: 2568,
      con_tratamiento: 301,
      validos: 259,
      invalidados: 42,
      icu1: 5764,
      icu2: 9700,
      icu3: 7443,
      icu4: 2568,
      blackcode: 2568,
      sla_p50_min: 5.91,
      sla_p90_min: 11.34,
      trat_5min: 10,
      trat_2h: 289,
    },
    daily: [
      { dia: "2026-06-01", total: 550, icu4: 60, gestionables: 60, validos: 5 },
      {
        dia: "2026-06-02",
        total: 1104,
        icu4: 133,
        gestionables: 133,
        validos: 14,
      },
      {
        dia: "2026-06-03",
        total: 1002,
        icu4: 95,
        gestionables: 95,
        validos: 13,
      },
      {
        dia: "2026-06-04",
        total: 1223,
        icu4: 127,
        gestionables: 127,
        validos: 10,
      },
      { dia: "2026-06-05", total: 812, icu4: 97, gestionables: 97, validos: 4 },
      { dia: "2026-06-06", total: 807, icu4: 72, gestionables: 72, validos: 3 },
      { dia: "2026-06-07", total: 584, icu4: 49, gestionables: 49, validos: 6 },
      {
        dia: "2026-06-08",
        total: 710,
        icu4: 80,
        gestionables: 80,
        validos: 12,
      },
      {
        dia: "2026-06-09",
        total: 1143,
        icu4: 129,
        gestionables: 129,
        validos: 18,
      },
      {
        dia: "2026-06-10",
        total: 1027,
        icu4: 109,
        gestionables: 109,
        validos: 9,
      },
      { dia: "2026-06-11", total: 767, icu4: 77, gestionables: 77, validos: 7 },
      {
        dia: "2026-06-12",
        total: 850,
        icu4: 99,
        gestionables: 99,
        validos: 13,
      },
      {
        dia: "2026-06-13",
        total: 1064,
        icu4: 101,
        gestionables: 101,
        validos: 11,
      },
      { dia: "2026-06-14", total: 669, icu4: 81, gestionables: 81, validos: 3 },
      {
        dia: "2026-06-15",
        total: 746,
        icu4: 68,
        gestionables: 68,
        validos: 10,
      },
      {
        dia: "2026-06-16",
        total: 1337,
        icu4: 124,
        gestionables: 124,
        validos: 31,
      },
      { dia: "2026-06-17", total: 794, icu4: 75, gestionables: 75, validos: 5 },
      {
        dia: "2026-06-18",
        total: 1134,
        icu4: 133,
        gestionables: 133,
        validos: 12,
      },
      { dia: "2026-06-19", total: 794, icu4: 65, gestionables: 65, validos: 3 },
      {
        dia: "2026-06-20",
        total: 1108,
        icu4: 97,
        gestionables: 97,
        validos: 9,
      },
      {
        dia: "2026-06-21",
        total: 393,
        icu4: 32,
        gestionables: 32,
        validos: 12,
      },
      { dia: "2026-06-22", total: 618, icu4: 53, gestionables: 53, validos: 5 },
      {
        dia: "2026-06-23",
        total: 911,
        icu4: 72,
        gestionables: 72,
        validos: 11,
      },
      {
        dia: "2026-06-24",
        total: 1222,
        icu4: 125,
        gestionables: 125,
        validos: 10,
      },
      { dia: "2026-06-25", total: 810, icu4: 83, gestionables: 83, validos: 5 },
      {
        dia: "2026-06-26",
        total: 996,
        icu4: 119,
        gestionables: 119,
        validos: 16,
      },
      {
        dia: "2026-06-27",
        total: 1059,
        icu4: 104,
        gestionables: 104,
        validos: 2,
      },
      { dia: "2026-06-28", total: 493, icu4: 46, gestionables: 46, validos: 0 },
      { dia: "2026-06-29", total: 370, icu4: 35, gestionables: 35, validos: 0 },
      { dia: "2026-06-30", total: 378, icu4: 28, gestionables: 28, validos: 0 },
    ],
    route: [
      { dim: "Ruta 1", total: 5479, icu4: 639 },
      { dim: "Ruta 13", total: 3918, icu4: 242 },
      { dim: "Ruta 3", total: 2289, icu4: 199 },
      { dim: "Ruta 4", total: 2026, icu4: 247 },
      { dim: "Ruta 23", total: 1600, icu4: 143 },
      { dim: "Ruta 6", total: 1358, icu4: 132 },
      { dim: "Ruta 2", total: 1164, icu4: 125 },
      { dim: "Ruta 7", total: 974, icu4: 117 },
      { dim: "Ruta 5", total: 942, icu4: 98 },
      { dim: "Ruta 14", total: 567, icu4: 37 },
    ],
    carrier: [
      { dim: "Transportista 1", total: 14591, icu4: 1338 },
      { dim: "Transportista 3", total: 1017, icu4: 104 },
      { dim: "Transportista 2", total: 997, icu4: 91 },
      { dim: "Transportista 5", total: 690, icu4: 59 },
      { dim: "Transportista 4", total: 564, icu4: 52 },
      { dim: "Transportista 14", total: 538, icu4: 77 },
      { dim: "Transportista 16", total: 488, icu4: 56 },
      { dim: "Transportista 7", total: 467, icu4: 68 },
      { dim: "Transportista 10", total: 438, icu4: 45 },
      { dim: "Transportista 6", total: 379, icu4: 39 },
    ],
    driver: [
      { dim: "Conductor 1", total: 661, icu4: 86 },
      { dim: "Conductor 6", total: 640, icu4: 20 },
      { dim: "Conductor 3", total: 635, icu4: 64 },
      { dim: "Conductor 2", total: 606, icu4: 62 },
      { dim: "Conductor 4", total: 592, icu4: 43 },
      { dim: "Conductor 5", total: 579, icu4: 63 },
      { dim: "Conductor 7", total: 545, icu4: 53 },
      { dim: "Conductor 8", total: 498, icu4: 57 },
      { dim: "Conductor 49", total: 384, icu4: 25 },
      { dim: "Conductor 70", total: 376, icu4: 30 },
    ],
  },
};
