# Run with turbo-repo as the project base directory.
sonar.projectKey=microboxlabs_miot-dashboard-server
sonar.projectName=MIOT Dashboard Server
sonar.organization=microboxlabs
sonar.sources=packages/miot-dashboard-server/src,packages/miot-dashboard-contract/src,packages/miot-dashboard-ui/src
sonar.tests=packages/miot-dashboard-server/src,packages/miot-dashboard-contract/src,packages/miot-dashboard-ui/src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/*.d.ts
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=packages/miot-dashboard-server/coverage/lcov.info,packages/miot-dashboard-contract/coverage/lcov.info,packages/miot-dashboard-ui/coverage/lcov.info
